INSERT INTO weather_conditions (id, description) VALUES
(1, 'Overcast'),
(2, 'Clear'),
(3, 'Fog'),
(4, 'Mostly Cloudy'),
(5, 'Partly Cloudy'),
(6, 'Scattered Clouds'),
(7, 'Light Freezing Rain'),
(8, 'Haze'),
(9, 'Mist'),
(10, 'Light Rain'),
(11, 'Light Snow'),
(12, 'Fair'),
(13, 'Light Freezing Fog'),
(14, 'Cloudy'),
(15, 'Drizzle'),
(16, 'Snow'),
(17, 'Heavy Rain'),
(18, 'Patches of Fog'),
(19, 'Rain'),
(20, 'Light Freezing Drizzle'),
(21, 'Light Drizzle'),
(22, 'Heavy Thunderstorms and Snow'),
(23, 'Heavy Thunderstorms and Rain'),
(24, 'Smoke'),
(25, 'Thunderstorms and Rain'),
(26, 'Light Ice Pellets'),
(27, 'Thunder'),
(28, 'Heavy Snow'),
(29, 'Fair / Windy'),
(30, 'Blowing Snow'),
(31, 'Partly Cloudy / Windy'),
(32, 'N/A Precipitation'),
(33, 'Shallow Fog'),
(34, 'Light Thunderstorms and Rain'),
(35, 'Thunder in the Vicinity'),
(36, 'T-Storm'),
(37, 'Light Rain Showers'),
(38, 'Cloudy / Windy'),
(39, 'Blowing Dust / Windy'),
(40, 'Heavy T-Storm / Windy'),
(41, 'Mostly Cloudy / Windy'),
(42, 'Light Snow Showers'),
(43, 'Showers in the Vicinity'),
(44, 'Light Thunderstorms and Snow'),
(45, 'Light Rain with Thunder'),
(46, 'Light Rain / Windy'),
(47, 'Heavy T-Storm'),
(48, 'Heavy Drizzle'),
(49, 'Ice Pellets'),
(50, 'Snow Grains'),
(51, 'Rain / Windy'),
(52, 'Snow Showers'),
(53, 'Freezing Rain / Windy'),
(54, 'Light Snow / Windy'),
(55, 'Heavy Rain / Windy'),
(56, 'Thunderstorm'),
(57, 'Wintry Mix'),
(58, 'Smoke / Windy'),
(59, 'Light Snow and Sleet'),
(60, 'Widespread Dust'),
(61, 'Small Hail'),
(62, 'Light Rain Shower'),
(63, 'Fog / Windy'),
(64, 'T-Storm / Windy'),
(65, 'Haze / Windy'),
(66, 'Thunder / Windy'),
(67, 'Wintry Mix / Windy'),
(68, 'Snow and Sleet / Windy'),
(69, 'Snow / Windy'),
(70, 'Heavy Snow / Windy'),
(71, 'Drizzle and Fog'),
(72, 'Blowing Snow / Windy'),
(73, 'Light Drizzle / Windy'),
(74, 'Squalls / Windy'),
(75, 'Snow and Sleet'),
(76, 'Rain Shower'),
(77, 'Heavy Sleet'),
(78, 'Freezing Rain'),
(79, 'Light Freezing Rain / Windy'),
(80, 'Hail'),
(81, 'Light Snow Shower / Windy'),
(82, 'Sleet'),
(83, 'Light Snow with Thunder'),
(84, 'Light Sleet'),
(85, 'Light Snow and Sleet / Windy'),
(86, 'Mist / Windy'),
(87, 'Sleet / Windy'),
(88, 'Blowing Dust'),
(89, 'Light Snow Shower'),
(90, 'Rain Shower / Windy');
