-- INSERT statements for AIRPORTS table
-- Generated automatically from AIRPORTS_COM_NOME.csv

INSERT INTO AIRPORTS (Airport_Code, Timezone, Airport_Name) VALUES
('KCMH', 'US/Eastern', 'John Glenn Columbus International Airport'),
('KROA', 'US/Eastern', 'Roanoke–Blacksburg Regional Airport'),
('KBED', 'US/Eastern', 'Laurence G Hanscom Field'),
('KARR', 'US/Central', 'Aurora Municipal Airport'),
('KCGS', 'US/Eastern', 'College Park Airport'),
('KLUK', 'US/Eastern', 'Cincinnati Municipal Airport Lunken Field'),
('KOXC', 'US/Eastern', 'Waterbury Oxford Airport'),
('KMDW', 'US/Central', 'Chicago Midway International Airport'),
('KJFK', 'US/Eastern', 'John F Kennedy International Airport'),
('KSWF', 'US/Eastern', 'New York Stewart International Airport'),
('KTZR', 'US/Eastern', 'Bolton Field'),
('KHPN', 'US/Eastern', 'Westchester County Airport'),
('KFNT', 'US/Eastern', 'Bishop International Airport'),
('KLOM', 'US/Eastern', 'Wings Field'),
('KMCJ', 'US/Central', 'Salina Municipal Airport'),
('KLGA', 'US/Eastern', 'LaGuardia Airport'),
('KATL', 'US/Eastern', 'Hartsfield Jackson Atlanta International Airport'),
('KPTW', 'US/Eastern', 'Heritage Field'),
('KBDL', 'US/Eastern', 'Bradley International Airport'),
('KDAL', 'US/Central', 'Dallas Love Field'),
('KAGC', 'US/Eastern', 'Allegheny County Airport'),
('KFIG', 'US/Eastern', 'Clearfield Lawrence Airport'),
('KDVO', 'US/Pacific', 'Marin County Airport - Gnoss Field'),
('KVLL', 'US/Eastern', 'Oakland Troy Airport'),
('KMTC', 'US/Eastern', 'Selfridge Air National Guard Base Airport'),
('KBKL', 'US/Eastern', 'Burke Lakefront Airport'),
('KSLB', 'US/Central', 'Storm Lake Municipal Airport'),
('KMWC', 'US/Central', 'Lawrence J Timmerman Airport'),
('KGYY', 'US/Central', 'Gary Chicago International Airport'),
('KBVY', 'US/Eastern', 'Beverly Regional Airport'),
('KD95', 'US/Eastern', 'Dupont-Lapeer Airport'),
('KLWM', 'US/Eastern', 'Lawrence Municipal Airport'),
('KBDR', 'US/Eastern', 'Igor I Sikorsky Memorial Airport'),
('KIKV', 'US/Central', 'Ankeny Regional Airport'),
('KOQN', 'US/Eastern', 'Brandywine Regional Airport'),
('KRNT', 'US/Pacific', 'Renton Municipal Airport'),
('KALB', 'US/Eastern', 'Albany International Airport'),
('KMLE', 'US/Central', 'Millard Airport'),
('KEWR', 'US/Eastern', 'Newark Liberty International Airport'),
('KDET', 'US/Eastern', 'Coleman A. Young Municipal Airport'),
('KORD', 'US/Central', 'Chicago O''Hare International Airport'),
('KOKH', 'US/Pacific', 'AJ Eisenberg Airport'),
('KDAY', 'US/Eastern', 'James M Cox Dayton International Airport'),
('KOJC', 'US/Central', 'Johnson County Executive Airport'),
('KLVN', 'US/Central', 'Airlake Airport'),
('KLOU', 'US/Eastern', 'Bowman Field'),
('K3A6', 'US/Pacific', 'Pacific City State Airport'),
('KIDA', 'US/Mountain', 'Idaho Falls Regional Airport'),
('KUKT', 'US/Eastern', 'Quakertown Airport'),
('KDSM', 'US/Central', 'Des Moines International Airport'),
('KRME', 'US/Eastern', 'Griffiss International Airport'),
('KPDX', 'US/Pacific', 'Portland International Airport'),
('KRJD', 'US/Eastern', 'Ridgely Airpark'),
('KRDG', 'US/Eastern', 'Reading Regional Airport (Carl A Spaatz Field)'),
('KMCC', 'US/Pacific', 'McClellan Airfield'),
('KPNE', 'US/Eastern', 'Northeast Philadelphia Airport'),
('KLNS', 'US/Eastern', 'Lancaster Airport'),
('KMMK', 'US/Eastern', 'Meriden Markham Municipal Airport'),
('KDMW', 'US/Eastern', 'Carroll County Regional Jack B Poage Field'),
('KCEF', 'US/Eastern', 'Westover Metropolitan Airport / Westover Air Reserve Base'),
('KPSF', 'US/Eastern', 'Pittsfield Municipal Airport'),
('KAFF', 'US/Mountain', 'USAF Academy Airfield'),
('KBOS', 'US/Eastern', 'Logan International Airport'),
('KLDJ', 'US/Eastern', 'Linden Airport'),
('K4I3', 'US/Eastern', 'Knox County Airport'),
('KJRB', 'US/Eastern', 'Downtown Manhattan Heliport'),
('KORH', 'US/Eastern', 'Worcester Regional Airport'),
('KIAD', 'US/Eastern', 'Washington Dulles International Airport'),
('KSGS', 'US/Central', 'South St Paul Municipal Airport/Richard E Fleming Field'),
('KVIS', 'US/Pacific', 'Visalia Municipal Airport'),
('KOSU', 'US/Eastern', 'The Ohio State University Airport - Don Scott Field'),
('KUCP', 'US/Eastern', 'New Castle Municipal Airport'),
('KRDU', 'US/Eastern', 'Raleigh Durham International Airport'),
('KJYO', 'US/Eastern', 'Leesburg Executive Airport'),
('KGTF', 'US/Mountain', 'Great Falls International Airport'),
('KIRS', 'US/Eastern', 'Kirsch Municipal Airport'),
('KBWI', 'US/Eastern', 'Baltimore/Washington International Thurgood Marshall Airport'),
('KSTL', 'US/Central', 'St. Louis Lambert International Airport'),
('KOFF', 'US/Central', 'Offutt Air Force Base'),
('KMKC', 'US/Central', 'Charles B. Wheeler Downtown Airport'),
('KAMW', 'US/Central', 'Ames Municipal Airport'),
('KTHV', 'US/Eastern', 'York Airport'),
('KPHL', 'US/Eastern', 'Philadelphia International Airport'),
('KOMA', 'US/Central', 'Eppley Airfield'),
('KPWK', 'US/Central', 'Chicago Executive Airport'),
('KSMQ', 'US/Eastern', 'Somerset Airport'),
('KIGQ', 'US/Central', 'Lansing Municipal Airport'),
('KCLE', 'US/Eastern', 'Cleveland Hopkins International Airport'),
('KDCA', 'US/Eastern', 'Ronald Reagan Washington National Airport'),
('KCXY', 'US/Eastern', 'Capital City Airport'),
('KSEA', 'US/Pacific', 'Seattle–Tacoma International Airport'),
('KFTY', 'US/Eastern', 'Fulton County Airport Brown Field'),
('KMGE', 'US/Eastern', 'Dobbins Air Reserve Base'),
('KVES', 'US/Eastern', 'Darke County Airport'),
('KPWT', 'US/Pacific', 'Bremerton National Airport'),
('KNFJ', 'US/Central', 'Choctaw Nolf Airport'),
('KPLU', 'US/Pacific', 'Pierce County-Thun Field'),
('KTIW', 'US/Pacific', 'Tacoma Narrows Airport'),
('KSDF', 'US/Eastern', 'Louisville Muhammad Ali International Airport'),
('KPDK', 'US/Eastern', 'DeKalb Peachtree Airport'),
('KDUH', 'US/Eastern', 'Toledo Suburban Airport'),
('KTOL', 'US/Eastern', 'Eugene F. Kranz Toledo Express Airport'),
('KRNO', 'US/Pacific', 'Reno Tahoe International Airport'),
('KADW', 'US/Eastern', 'Joint Base Andrews'),
('KCCR', 'US/Pacific', 'Buchanan Field'),
('KGRR', 'US/Eastern', 'Gerald R. Ford International Airport'),
('KDXR', 'US/Eastern', 'Danbury Municipal Airport'),
('KSLC', 'US/Mountain', 'Salt Lake City International Airport'),
('KCLT', 'US/Eastern', 'Charlotte Douglas International Airport'),
('K21D', 'US/Central', 'Lake Elmo Airport'),
('KPSM', 'US/Eastern', 'Portsmouth International at Pease Airport'),
('KRIC', 'US/Eastern', 'Richmond International Airport'),
('KE16', 'US/Pacific', 'San Martin Airport'),
('KILG', 'US/Eastern', 'Wilmington Airport'),
('KFWA', 'US/Eastern', 'Fort Wayne International Airport'),
('KTTD', 'US/Pacific', 'Portland Troutdale Airport'),
('KBFI', 'US/Pacific', 'Boeing Field King County International Airport'),
('KISP', 'US/Eastern', 'Long Island Mac Arthur Airport'),
('KPOU', 'US/Eastern', 'Dutchess County Airport'),
('KUGN', 'US/Central', 'Waukegan National Airport'),
('KFFO', 'US/Eastern', 'Wright-Patterson Air Force Base'),
('KDPA', 'US/Central', 'Dupage Airport'),
('KSCH', 'US/Eastern', 'Schenectady County Airport'),
('KCCY', 'US/Central', 'Northeast Iowa Regional Airport'),
('KPIT', 'US/Eastern', 'Pittsburgh International Airport'),
('KSYR', 'US/Eastern', 'Syracuse Hancock International Airport'),
('KMHR', 'US/Pacific', 'Sacramento Mather Airport'),
('KK22', 'US/Eastern', 'Big Sandy Regional Airport'),
('KPMD', 'US/Pacific', 'Palmdale Regional Airport / USAF Plant 42 Airport'),
('KPAE', 'US/Pacific', 'Seattle Paine Field International Airport'),
('KAND', 'US/Eastern', 'Anderson Regional Airport'),
('KFDK', 'US/Eastern', 'Frederick Municipal Airport'),
('KGON', 'US/Eastern', 'Groton New London Airport'),
('KAEL', 'US/Central', 'Albert Lea Municipal Airport'),
('KDAW', 'US/Eastern', 'Skyhaven Airport'),
('KSFZ', 'US/Eastern', 'North Central State Airport'),
('KPTK', 'US/Eastern', 'Oakland County International Airport'),
('KSUU', 'US/Pacific', 'Travis Air Force Base'),
('KSNC', 'US/Eastern', 'Chester Airport'),
('KPVD', 'US/Eastern', 'Theodore Francis Green State Airport'),
('KU78', 'US/Mountain', 'Allen H Tigert Airport'),
('KFCM', 'US/Central', 'Flying Cloud Airport'),
('KPDT', 'US/Pacific', 'Eastern Oregon Regional Airport at Pendleton'),
('KMGY', 'US/Eastern', 'Dayton-Wright Brothers Airport'),
('KAUN', 'US/Pacific', 'Auburn Municipal Airport'),
('KRYV', 'US/Central', 'Watertown Municipal Airport'),
('KEUG', 'US/Pacific', 'Mahlon Sweet Field'),
('KANE', 'US/Central', 'Anoka County-Blaine (Janes Field) Airport'),
('KLBE', 'US/Eastern', 'Arnold Palmer Regional Airport'),
('KBGR', 'US/Eastern', 'Bangor International Airport'),
('KOPN', 'US/Eastern', 'Thomaston Upson County Airport'),
('KRBD', 'US/Central', 'Dallas Executive Airport'),
('KSEZ', 'US/Mountain', 'Sedona Airport'),
('KPVU', 'US/Mountain', 'Provo-Utah Lake International Airport'),
('KVNC', 'US/Eastern', 'Venice Municipal Airport'),
('K9A1', 'US/Eastern', 'Covington Municipal Airport'),
('KTDZ', 'US/Eastern', 'Toledo Executive Airport'),
('KMPO', 'US/Eastern', 'Pocono Mountains Municipal Airport'),
('KHWD', 'US/Pacific', 'Hayward Executive Airport'),
('KUNI', 'US/Eastern', 'Ohio University Airport'),
('KMCI', 'US/Central', 'Kansas City International Airport'),
('KFKS', 'US/Eastern', 'Frankfort Dow Memorial Field'),
('KAPG', 'US/Eastern', 'Phillips Army Air Field'),
('KMIC', 'US/Central', 'Crystal Airport'),
('KVAY', 'US/Eastern', 'South Jersey Regional Airport'),
('KDFW', 'US/Central', 'Dallas Fort Worth International Airport'),
('KMQY', 'US/Central', 'Smyrna Airport'),
('KAPA', 'US/Mountain', 'Centennial Airport'),
('KLGD', 'US/Pacific', 'La Grande/Union County Airport'),
('KDTW', 'US/Eastern', 'Detroit Metropolitan Wayne County Airport'),
('KAKR', 'US/Eastern', 'Akron Fulton International Airport'),
('KACY', 'US/Eastern', 'Atlantic City International Airport'),
('KINJ', 'US/Central', 'Hillsboro Municipal Airport'),
('KTTF', 'US/Eastern', 'Custer Airport'),
('KLOT', 'US/Central', 'Lewis University Airport'),
('KHSP', 'US/Eastern', 'Ingalls Field'),
('KMKJ', 'US/Eastern', 'Mountain Empire Airport'),
('KBIV', 'US/Eastern', 'West Michigan Regional Airport'),
('KDAA', 'US/Eastern', 'Davison Army Air Field'),
('KBVS', 'US/Pacific', 'Skagit Regional Airport'),
('KMSP', 'US/Central', 'Minneapolis–Saint Paul International Airport / Wold–Chamberlain Field'),
('KLWB', 'US/Eastern', 'Greenbrier Valley Airport'),
('KCGF', 'US/Eastern', 'Cuyahoga County Airport'),
('KFKA', 'US/Central', 'Fillmore County Airport'),
('KAWO', 'US/Pacific', 'Arlington Municipal Airport'),
('KBUF', 'US/Eastern', 'Buffalo Niagara International Airport'),
('KBUR', 'US/Pacific', 'Hollywood Burbank Airport'),
('KTEB', 'US/Eastern', 'Teterboro Airport'),
('KIOB', 'US/Eastern', 'Mount Sterling Montgomery County Airport'),
('KVTA', 'US/Eastern', 'Newark Heath Airport'),
('KCPS', 'US/Central', 'St Louis Downtown Airport'),
('KSEG', 'US/Eastern', 'Penn Valley Airport'),
('KNEW', 'US/Central', 'Lakefront Airport'),
('KTME', 'US/Central', 'Houston Executive Airport'),
('KRAL', 'US/Pacific', 'Riverside Municipal Airport'),
('KERY', 'US/Eastern', 'Luce County Airport'),
('KMJX', 'US/Eastern', 'Ocean County Airport'),
('KIJD', 'US/Eastern', 'Windham Airport'),
('KLCK', 'US/Eastern', 'Rickenbacker International Airport'),
('KSCK', 'US/Pacific', 'Stockton Metropolitan Airport'),
('KAPC', 'US/Pacific', 'Napa County Airport'),
('KSFF', 'US/Pacific', 'Felts Field'),
('KXFL', 'US/Eastern', 'Flagler Executive Airport'),
('KTYR', 'US/Central', 'Tyler Pounds Regional Airport'),
('KFRG', 'US/Eastern', 'Republic Airport'),
('KJQF', 'US/Eastern', 'Concord-Padgett Regional Airport'),
('KLGB', 'US/Pacific', 'Long Beach Airport (Daugherty Field)'),
('KLVK', 'US/Pacific', 'Livermore Municipal Airport'),
('KTEX', 'US/Mountain', 'Telluride Regional Airport'),
('KEYE', 'US/Eastern', 'Eagle Creek Airpark'),
('KBJC', 'US/Mountain', 'Rocky Mountain Metropolitan Airport'),
('KSMF', 'US/Pacific', 'Sacramento International Airport'),
('KU42', 'US/Mountain', 'South Valley Regional Airport'),
('KENW', 'US/Central', 'Kenosha Regional Airport'),
('KOLZ', 'US/Central', 'Oelwein Municipal Airport'),
('KBNA', 'US/Central', 'Nashville International Airport'),
('KBAK', 'US/Eastern', 'Columbus Municipal Airport'),
('KZZV', 'US/Eastern', 'Zanesville Municipal Airport'),
('KHFD', 'US/Eastern', 'Hartford Brainard Airport'),
('KBKF', 'US/Mountain', 'Buckley Space Force Base'),
('KGRF', 'US/Pacific', 'Gray Army Air Field'),
('KFWS', 'US/Central', 'Fort Worth Spinks Airport'),
('KMKT', 'US/Central', 'Mankato Regional Airport'),
('KLSV', 'US/Pacific', 'Nellis Air Force Base'),
('KAVL', 'US/Eastern', 'Asheville Regional Airport'),
('KHGR', 'US/Eastern', 'Hagerstown Regional Richard A Henson Field'),
('KMQS', 'US/Eastern', 'Chester County G O Carlson Airport'),
('KCHD', 'US/Mountain', 'Chandler Municipal Airport'),
('KGSO', 'US/Eastern', 'Piedmont Triad International Airport'),
('KLXT', 'US/Central', 'Lee''s Summit Municipal Airport'),
('KPHX', 'US/Mountain', 'Phoenix Sky Harbor International Airport'),
('KCID', 'US/Central', 'The Eastern Iowa Airport'),
('KVCB', 'US/Pacific', 'Nut Tree Airport'),
('KCAK', 'US/Eastern', 'Akron Canton Regional Airport'),
('KIKW', 'US/Eastern', 'Jack Barstow Airport'),
('KEDU', 'US/Pacific', 'University Airport'),
('KMGJ', 'US/Eastern', 'Orange County Airport'),
('KF46', 'US/Central', 'Rockwall Municipal Airport'),
('KHQZ', 'US/Central', 'Mesquite Metro Airport'),
('KFME', 'US/Eastern', 'Tipton Airport'),
('KFEW', 'US/Mountain', 'Francis E Warren Air Force Base'),
('KDCU', 'US/Central', 'Pryor Field Regional Airport'),
('KMDT', 'US/Eastern', 'Harrisburg International Airport'),
('KPVF', 'US/Pacific', 'Placerville Airport'),
('KAZO', 'US/Eastern', 'Kalamazoo Battle Creek International Airport'),
('KIMM', 'US/Eastern', 'Immokalee Regional Airport'),
('KRIV', 'US/Pacific', 'March Air Reserve Base'),
('KBTA', 'US/Central', 'Blair Executive Airport'),
('KGPM', 'US/Central', 'Grand Prairie Municipal Airport'),
('KSTS', 'US/Pacific', 'Charles M. Schulz Sonoma County Airport'),
('KYIP', 'US/Eastern', 'Willow Run Airport'),
('KAUG', 'US/Eastern', 'Augusta State Airport'),
('KLBR', 'US/Central', 'Clarksville Red River City-J D Trissell Field'),
('KMQJ', 'US/Eastern', 'Indianapolis Regional Airport'),
('KMBS', 'US/Eastern', 'MBS International Airport'),
('KTIK', 'US/Central', 'Tinker Air Force Base'),
('KXLL', 'US/Eastern', 'Allentown Queen City Municipal Airport'),
('KTTN', 'US/Eastern', 'Trenton Mercer Airport'),
('KEQY', 'US/Eastern', 'Charlotte-Monroe Executive Airport'),
('KHOU', 'US/Central', 'William P Hobby Airport'),
('KGEV', 'US/Eastern', 'Ashe County Airport'),
('KJVL', 'US/Central', 'Southern Wisconsin Regional Airport'),
('KTCM', 'US/Pacific', 'McChord Air Force Base'),
('KSGF', 'US/Central', 'Springfield Branson National Airport'),
('KSFM', 'US/Eastern', 'Sanford Seacoast Regional Airport'),
('KSAT', 'US/Central', 'San Antonio International Airport'),
('KGAI', 'US/Eastern', 'Montgomery County Airpark'),
('KHVN', 'US/Eastern', 'Tweed New Haven Airport'),
('KCHO', 'US/Eastern', 'Charlottesville Albemarle Airport'),
('KTEW', 'US/Eastern', 'Mason Jewett Field'),
('KTBN', 'US/Central', 'Waynesville-St. Robert Regional Airport-Forney Field'),
('KVGT', 'US/Pacific', 'North Las Vegas Metropolitan International Airport'),
('KOKV', 'US/Eastern', 'Winchester Regional Airport'),
('KDSV', 'US/Eastern', 'Dansville Municipal Airport'),
('KCDW', 'US/Eastern', 'Essex County Airport'),
('KMKE', 'US/Central', 'General Mitchell International Airport'),
('KCOS', 'US/Mountain', 'City of Colorado Springs Municipal Airport'),
('KABE', 'US/Eastern', 'Lehigh Valley International Airport'),
('KSFO', 'US/Pacific', 'San Francisco International Airport'),
('K27A', 'US/Eastern', 'Elbert County Airport Patz Field'),
('KEDJ', 'US/Eastern', 'Bellefontaine Regional Airport'),
('KHMZ', 'US/Eastern', 'Bedford County Airport'),
('K9L2', 'US/Pacific', 'Edwards Af Aux North Base Airport'),
('KIAH', 'US/Central', 'George Bush Intercontinental Houston Airport'),
('KHEF', 'US/Eastern', 'Manassas Regional Airport/Harry P. Davis Field'),
('KLSE', 'US/Central', 'La Crosse Regional Airport'),
('KSUS', 'US/Central', 'Spirit of St Louis Airport'),
('KLCI', 'US/Eastern', 'Laconia Municipal Airport'),
('KFTW', 'US/Central', 'Fort Worth Meacham International Airport'),
('KPAN', 'US/Mountain', 'Payson Airport'),
('KEWB', 'US/Eastern', 'New Bedford Regional Airport'),
('KATT', 'US/Central', 'Central City Municipal - Larry Reineke Field'),
('KOKC', 'US/Central', 'Will Rogers World Airport'),
('KSPI', 'US/Central', 'Abraham Lincoln Capital Airport'),
('KSTP', 'US/Central', 'Saint Paul Downtown Holman Field'),
('KLAN', 'US/Eastern', 'Capital City Airport'),
('KBGM', 'US/Eastern', 'Greater Binghamton/Edwin A Link field'),
('KAGS', 'US/Eastern', 'Augusta Regional At Bush Field'),
('KDYL', 'US/Eastern', 'Doylestown Airport'),
('KPHN', 'US/Eastern', 'St Clair County International Airport'),
('KORE', 'US/Eastern', 'Orange Municipal Airport'),
('KSTE', 'US/Central', 'Stevens Point Municipal Airport'),
('KLZU', 'US/Eastern', 'Gwinnett County Briscoe Field'),
('KSGJ', 'US/Eastern', 'Northeast Florida Regional Airport'),
('KMFD', 'US/Eastern', 'Mansfield Lahm Regional Airport'),
('KDDC', 'US/Central', 'Dodge City Regional Airport'),
('KMKG', 'US/Eastern', 'Muskegon County Airport'),
('KLAF', 'US/Eastern', 'Purdue University Airport'),
('KMLI', 'US/Central', 'Quad City International Airport'),
('KAAA', 'US/Central', 'Logan County Airport'),
('KSHD', 'US/Eastern', 'Shenandoah Valley Regional Airport'),
('KPYM', 'US/Eastern', 'Plymouth Municipal Airport'),
('KNUQ', 'US/Pacific', 'Moffett Federal Airfield'),
('KSAC', 'US/Pacific', 'Sacramento Executive Airport'),
('KHRI', 'US/Pacific', 'Hermiston Municipal Airport'),
('KTUS', 'US/Mountain', 'Tucson International Airport / Morris Air National Guard Base'),
('KLUA', 'US/Eastern', 'Luray Caverns Airport'),
('KAIK', 'US/Eastern', 'Aiken Regional Airport'),
('KADS', 'US/Central', 'Addison Airport'),
('KLHQ', 'US/Eastern', 'Fairfield County Airport'),
('KEKO', 'US/Pacific', 'Elko Regional Airport'),
('KAHN', 'US/Eastern', 'Athens Ben Epps Airport'),
('KUES', 'US/Central', 'Waukesha County Airport'),
('KTAN', 'US/Eastern', 'Taunton Municipal King Field'),
('KERI', 'US/Eastern', 'Erie International Tom Ridge Field'),
('KBIF', 'US/Mountain', 'Biggs Army Air Field (Fort Bliss)'),
('KKLS', 'US/Pacific', 'Southwest Washington Regional Airport'),
('K01M', 'US/Central', 'Tishomingo County Airport'),
('KOUN', 'US/Central', 'University of Oklahoma Westheimer Airport'),
('KAUW', 'US/Central', 'Wausau Downtown Airport'),
('KHAO', 'US/Eastern', 'Butler Co Regional Airport - Hogan Field'),
('KBTL', 'US/Eastern', 'Battle Creek Executive Airport at Kellogg Field'),
('KFKN', 'US/Eastern', 'Franklin Regional Airport'),
('KRTS', 'US/Pacific', 'Reno-Stead Airport'),
('KONT', 'US/Pacific', 'Ontario International Airport'),
('KCMR', 'US/Mountain', 'H.A. Clark Memorial Field'),
('KLEE', 'US/Eastern', 'Leesburg International Airport'),
('KBKV', 'US/Eastern', 'Brooksville–Tampa Bay Regional Airport'),
('KEZF', 'US/Eastern', 'Shannon Airport'),
('KMSV', 'US/Eastern', 'Sullivan County International Airport'),
('KSZT', 'US/Pacific', 'Sandpoint Airport'),
('KCRW', 'US/Eastern', 'Yeager Airport'),
('KTYQ', 'US/Eastern', 'Indianapolis Executive Airport'),
('KMUL', 'US/Eastern', 'Spence Airport'),
('KHZY', 'US/Eastern', 'Northeast Ohio Regional Airport'),
('KBLI', 'US/Pacific', 'Bellingham International Airport'),
('KI75', 'US/Central', 'Osceola Municipal Airport'),
('KFBL', 'US/Central', 'Faribault Municipal Airport-Liz Wall Strohfus Field'),
('KRDM', 'US/Pacific', 'Roberts Field'),
('KI69', 'US/Eastern', 'Clermont County Airport'),
('KRHV', 'US/Pacific', 'Reid-Hillview Airport of Santa Clara County'),
('K6A2', 'US/Eastern', 'Griffin Spalding County Airport'),
('KFIT', 'US/Eastern', 'Fitchburg Municipal Airport'),
('K11R', 'US/Central', 'Brenham Municipal Airport'),
('KHZX', 'US/Central', 'Isedor Iverson Airport'),
('KLFI', 'US/Eastern', 'Langley Air Force Base'),
('KARB', 'US/Eastern', 'Ann Arbor Municipal Airport'),
('KGKJ', 'US/Eastern', 'Port Meadville Airport'),
('KMEM', 'US/Central', 'Memphis International Airport'),
('KSTJ', 'US/Central', 'Rosecrans Memorial Airport'),
('KCVG', 'US/Eastern', 'Cincinnati Northern Kentucky International Airport'),
('KRZL', 'US/Central', 'Jasper County Airport'),
('KMHT', 'US/Eastern', 'Manchester-Boston Regional Airport'),
('KMTN', 'US/Eastern', 'Martin State Airport'),
('KBLM', 'US/Eastern', 'Monmouth Executive Airport'),
('KSJC', 'US/Pacific', 'Norman Y. Mineta San Jose International Airport'),
('KMLB', 'US/Eastern', 'Melbourne Orlando International Airport'),
('KCGE', 'US/Eastern', 'Cambridge Dorchester Airport'),
('KPIA', 'US/Central', 'General Wayne A. Downing Peoria International Airport'),
('KFNL', 'US/Mountain', 'Northern Colorado Regional Airport'),
('KFWN', 'US/Eastern', 'Sussex Airport'),
('KMLF', 'US/Mountain', 'Milford Municipal-Ben and Judy Briscoe Field'),
('KTRK', 'US/Pacific', 'Truckee Tahoe Airport'),
('KALO', 'US/Central', 'Waterloo Regional Airport'),
('KCLS', 'US/Pacific', 'Chehalis Centralia Airport'),
('KO69', 'US/Pacific', 'Petaluma Municipal Airport'),
('KDCY', 'US/Eastern', 'Daviess County Airport'),
('KLJF', 'US/Central', 'Litchfield Municipal Airport'),
('K0E0', 'US/Mountain', 'Moriarty Municipal Airport'),
('KFZY', 'US/Eastern', 'Oswego County Airport'),
('KEMT', 'US/Pacific', 'San Gabriel Valley Airport'),
('KAUS', 'US/Central', 'Austin Bergstrom International Airport'),
('KOZW', 'US/Eastern', 'Livingston County Spencer J. Hardy Airport'),
('KRMY', 'US/Eastern', 'Brooks Field'),
('KOGA', 'US/Mountain', 'Ogallala Municipal Airport Searle Field'),
('KCHS', 'US/Eastern', 'Charleston International Airport'),
('KLMT', 'US/Pacific', 'Crater Lake-Klamath Regional Airport'),
('KGPZ', 'US/Central', 'Grand Rapids Itasca Co-Gordon Newstrom field'),
('KVUO', 'US/Pacific', 'Pearson Field'),
('KOVE', 'US/Pacific', 'Oroville Municipal Airport'),
('KHTO', 'US/Eastern', 'Town of East Hampton Airport'),
('KLEX', 'US/Eastern', 'Blue Grass Airport'),
('KBNO', 'US/Pacific', 'Burns Municipal Airport'),
('KBAB', 'US/Pacific', 'Beale Air Force Base'),
('KELN', 'US/Pacific', 'Bowers Field'),
('KCVX', 'US/Eastern', 'Charlevoix Municipal Airport'),
('KSHN', 'US/Pacific', 'Sanderson Field'),
('KAID', 'US/Eastern', 'Anderson Municipal Darlington Field'),
('KDLL', 'US/Central', 'Baraboo Wisconsin Dells Regional Airport'),
('KCVH', 'US/Pacific', 'Hollister Municipal Airport'),
('KGCM', 'US/Central', 'Claremore Regional Airport'),
('KDUJ', 'US/Eastern', 'DuBois Regional Airport'),
('KBTP', 'US/Eastern', 'Pittsburgh/Butler Regional Airport'),
('KPHD', 'US/Eastern', 'Harry Clever Field'),
('KHYX', 'US/Eastern', 'Saginaw County H.W. Browne Airport'),
('KOFP', 'US/Eastern', 'Hanover County Municipal Airport'),
('KMIE', 'US/Eastern', 'Delaware County Johnson Field'),
('KBLU', 'US/Pacific', 'Blue Canyon Nyack Airport'),
('KRYY', 'US/Eastern', 'Cobb County International Airport-McCollum Field'),
('KBDH', 'US/Central', 'Willmar Municipal Airport John L Rice Field (2006)'),
('KDAN', 'US/Eastern', 'Danville Regional Airport'),
('KRYW', 'US/Central', 'Lago Vista Texas Rusty Allen Airport'),
('KEKM', 'US/Eastern', 'Elkhart Municipal Airport'),
('KFDY', 'US/Eastern', 'Findlay Airport'),
('KCZK', 'US/Pacific', 'Cascade Locks State Airport'),
('KBKW', 'US/Eastern', 'Raleigh County Memorial Airport'),
('KOLM', 'US/Pacific', 'Olympia Regional Airport'),
('KIOW', 'US/Central', 'Iowa City Municipal Airport'),
('KEIK', 'US/Mountain', 'Erie Municipal Airport'),
('KSGH', 'US/Eastern', 'Springfield-Beckley Municipal Airport'),
('KGSP', 'US/Eastern', 'Greenville Spartanburg International Airport'),
('KGRD', 'US/Eastern', 'Greenwood County Airport'),
('KOAK', 'US/Pacific', 'San Francisco Bay Oakland International Airport'),
('KMOD', 'US/Pacific', 'Modesto City Co-Harry Sham Field'),
('KFAT', 'US/Pacific', 'Fresno Yosemite International Airport'),
('KIXD', 'US/Central', 'New Century AirCenter Airport'),
('KMER', 'US/Pacific', 'Castle Airport'),
('KAVC', 'US/Eastern', 'Mecklenburg Brunswick Regional Airport'),
('KVYS', 'US/Central', 'Illinois Valley Regional Airport Walter A Duncan Field'),
('KAXH', 'US/Central', 'Houston Southwest Airport'),
('KBVI', 'US/Eastern', 'Beaver County Airport'),
('KTYS', 'US/Eastern', 'McGhee Tyson Airport'),
('KUAO', 'US/Pacific', 'Aurora State Airport'),
('KPRO', 'US/Central', 'Perry Municipal Airport'),
('KDLZ', 'US/Eastern', 'Delaware Municipal Airport'),
('KWVI', 'US/Pacific', 'Watsonville Municipal Airport'),
('KCHA', 'US/Eastern', 'Chattanooga Metropolitan Airport (Lovell Field)'),
('KHIO', 'US/Pacific', 'Portland Hillsboro Airport'),
('KF70', 'US/Pacific', 'French Valley Airport'),
('KVJI', 'US/Eastern', 'Virginia Highlands Airport'),
('KTDO', 'US/Pacific', 'Ed Carlson Memorial Field South Lewis County Airport'),
('KINW', 'US/Mountain', 'Winslow Lindbergh Regional Airport'),
('KJXN', 'US/Eastern', 'Jackson County Airport/Reynolds Field'),
('KMZZ', 'US/Eastern', 'Marion Municipal Airport'),
('KBAF', 'US/Eastern', 'Westfield-Barnes Regional Airport'),
('KANQ', 'US/Eastern', 'Tri State Steuben County Airport'),
('KSNS', 'US/Pacific', 'Salinas Municipal Airport'),
('KPCW', 'US/Eastern', 'Carl R Keller Field'),
('KGKY', 'US/Central', 'Arlington Municipal Airport'),
('KGEZ', 'US/Eastern', 'Shelbyville Municipal Airport'),
('KBLV', 'US/Central', 'Scott AFB/Midamerica Airport'),
('KEBS', 'US/Central', 'Webster City Municipal Airport'),
('KHYR', 'US/Central', 'Sawyer County Airport'),
('KOWD', 'US/Eastern', 'Norwood Memorial Airport'),
('KHWV', 'US/Eastern', 'Brookhaven Calabro Airport'),
('KSQL', 'US/Pacific', 'San Carlos Airport'),
('KONZ', 'US/Eastern', 'Grosse Ile Municipal Airport'),
('KL35', 'US/Pacific', 'Big Bear City Airport'),
('KL38', 'US/Central', 'Louisiana Regional Airport'),
('K48I', 'US/Eastern', 'Braxton County Airport'),
('KILN', 'US/Eastern', 'Wilmington Airpark'),
('KMUI', 'US/Eastern', 'Muir Army Air Field (Fort Indiantown Gap) Airport'),
('K0VG', 'US/Eastern', 'Lee County Airport'),
('KLWA', 'US/Eastern', 'South Haven Area Regional Airport'),
('KC29', 'US/Central', 'Middleton Municipal Morey Field'),
('KDEN', 'US/Mountain', 'Denver International Airport'),
('KMAN', 'US/Mountain', 'Nampa Municipal Airport'),
('KOGD', 'US/Mountain', 'Ogden Hinckley Airport'),
('KFCI', 'US/Eastern', 'Richmond Executive-Chesterfield County Airport'),
('KUNV', 'US/Eastern', 'State College Regional Airport'),
('KOKB', 'US/Pacific', 'Oceanside Municipal Airport'),
('KMSY', 'US/Central', 'Louis Armstrong New Orleans International Airport'),
('KCCO', 'US/Eastern', 'Newnan Coweta County Airport'),
('KC09', 'US/Central', 'Morris Municipal Airport James R. Washburn field'),
('KEVM', 'US/Central', 'Eveleth–Virginia Municipal Airport'),
('KO22', 'US/Pacific', 'Columbia Airport'),
('KFOK', 'US/Eastern', 'Francis S Gabreski Airport'),
('KCON', 'US/Eastern', 'Concord Municipal Airport'),
('KGWB', 'US/Eastern', 'De Kalb County Airport'),
('KVTI', 'US/Central', 'Vinton Veterans Memorial Airpark'),
('KRNH', 'US/Central', 'New Richmond Regional Airport'),
('KHKS', 'US/Central', 'Hawkins Field'),
('KDNL', 'US/Eastern', 'Daniel Field'),
('KFFT', 'US/Eastern', 'Capital City Airport'),
('KGSH', 'US/Eastern', 'Goshen Municipal Airport'),
('KFFC', 'US/Eastern', 'Peachtree City Falcon Field'),
('KMMU', 'US/Eastern', 'Morristown Municipal Airport'),
('KGLW', 'US/Central', 'Glasgow Municipal Airport'),
('KOTG', 'US/Central', 'Worthington Municipal Airport'),
('KORF', 'US/Eastern', 'Norfolk International Airport'),
('KPUC', 'US/Mountain', 'Carbon County Regional Airport / Buck Davis Field'),
('KABQ', 'US/Mountain', 'Albuquerque International Sunport'),
('KCBF', 'US/Central', 'Council Bluffs Municipal Airport'),
('K3I2', 'US/Eastern', 'Mason County Airport'),
('KEAU', 'US/Central', 'Chippewa Valley Regional Airport'),
('KPWA', 'US/Central', 'Wiley Post Airport'),
('KGOO', 'US/Pacific', 'Nevada County Airport'),
('KCOU', 'US/Central', 'Columbia Regional Airport'),
('KFLG', 'US/Mountain', 'Flagstaff Pulliam International Airport'),
('KAVP', 'US/Eastern', 'Wilkes Barre Scranton International Airport'),
('KAOH', 'US/Eastern', 'Lima Allen County Airport'),
('KUNU', 'US/Central', 'Dodge County Airport'),
('KATW', 'US/Central', 'Appleton International Airport'),
('KMKL', 'US/Central', 'McKellar-Sipes Regional Airport'),
('KIIY', 'US/Eastern', 'Washington Wilkes County Airport'),
('KRND', 'US/Central', 'Randolph Air Force Base'),
('KBUU', 'US/Central', 'Burlington Municipal Airport'),
('KPOC', 'US/Pacific', 'Brackett Field'),
('KCOE', 'US/Pacific', 'Coeur D''Alene Airport - Pappy Boyington Field'),
('KGOV', 'US/Eastern', 'Grayling Army Air Field'),
('K5W8', 'US/Eastern', 'Siler City Municipal Airport'),
('KASH', 'US/Eastern', 'Nashua Airport / Boire Field'),
('KSBD', 'US/Pacific', 'San Bernardino International Airport'),
('KLPR', 'US/Eastern', 'Lorain County Regional Airport'),
('KIPT', 'US/Eastern', 'Williamsport Regional Airport'),
('KRFD', 'US/Central', 'Chicago Rockford International Airport'),
('KPIH', 'US/Mountain', 'Pocatello Regional Airport'),
('KRNM', 'US/Pacific', 'Ramona Airport'),
('KAOO', 'US/Eastern', 'Altoona Blair County Airport'),
('KADG', 'US/Eastern', 'Lenawee County Airport'),
('KRNP', 'US/Eastern', 'Owosso Community Airport'),
('KGHG', 'US/Eastern', 'Marshfield Municipal George Harlow Field'),
('KTVL', 'US/Pacific', 'Lake Tahoe Airport'),
('KBCB', 'US/Eastern', 'Virginia Tech Montgomery Executive Airport'),
('KALW', 'US/Pacific', 'Walla Walla Regional Airport'),
('KBIL', 'US/Mountain', 'Billings Logan International Airport'),
('KAIG', 'US/Central', 'Langlade County Airport'),
('KJOT', 'US/Central', 'Joliet Regional Airport'),
('KMSN', 'US/Central', 'Dane County Regional Truax Field'),
('KCQT', 'US/Pacific', 'Pacific Valley Aviation Airport'),
('KPOV', 'US/Eastern', 'Portage County Regional Airport'),
('KDVN', 'US/Central', 'Davenport Municipal Airport'),
('KGEG', 'US/Pacific', 'Spokane International Airport'),
('KBOI', 'US/Mountain', 'Boise Air Terminal/Gowen Field'),
('KBJJ', 'US/Eastern', 'Wayne County Airport'),
('KSGR', 'US/Central', 'Sugar Land Regional Airport'),
('KVPC', 'US/Eastern', 'Cartersville Airport'),
('KD39', 'US/Central', 'Sauk Centre Municipal Airport'),
('KSUX', 'US/Central', 'Sioux Gateway Airport / Brigadier General Bud Day Field'),
('KEEN', 'US/Eastern', 'Dillant Hopkins Airport'),
('KDEH', 'US/Central', 'Decorah Municipal Airport'),
('KMWL', 'US/Central', 'Mineral Wells Regional Airport'),
('KELM', 'US/Eastern', 'Elmira Corning Regional Airport'),
('KVIH', 'US/Central', 'Rolla National Airport'),
('KMWM', 'US/Central', 'Windom Municipal Airport'),
('KHND', 'US/Pacific', 'Henderson Executive Airport'),
('KTOB', 'US/Central', 'Dodge Center Airport'),
('KOBE', 'US/Eastern', 'Okeechobee County Airport'),
('KMVE', 'US/Central', 'Montevideo Chippewa County Airport'),
('KSNA', 'US/Pacific', 'John Wayne Orange County International Airport'),
('KRMN', 'US/Eastern', 'Stafford Regional Airport'),
('KFBR', 'US/Mountain', 'Fort Bridger Airport'),
('KLAS', 'US/Pacific', 'Harry Reid International Airport'),
('KEOE', 'US/Eastern', 'Newberry County Airport'),
('KESN', 'US/Eastern', 'Easton Airport / Newnam Field'),
('KDKB', 'US/Central', 'DeKalb Taylor Municipal Airport'),
('KWDR', 'US/Eastern', 'Barrow County Airport'),
('KMTO', 'US/Central', 'Coles County Memorial Airport'),
('KPWM', 'US/Eastern', 'Portland International Jetport'),
('KSVH', 'US/Eastern', 'Statesville Regional Airport'),
('KIND', 'US/Eastern', 'Indianapolis International Airport'),
('KGPH', 'US/Central', 'Midwest National Air Center Airport'),
('KEDC', 'US/Central', 'Austin Executive Airport'),
('KROC', 'US/Eastern', 'Frederick Douglass Greater Rochester International Airport'),
('KMLD', 'US/Mountain', 'Malad City Airport'),
('KAXA', 'US/Central', 'Algona Municipal Airport'),
('KCLM', 'US/Pacific', 'William R Fairchild International Airport'),
('KSZL', 'US/Central', 'Whiteman Air Force Base'),
('KSUW', 'US/Central', 'Richard I Bong Memorial Airport'),
('KSOW', 'US/Mountain', 'Show Low Regional Airport'),
('KGVL', 'US/Eastern', 'Lee Gilmer Memorial Airport'),
('KMNN', 'US/Eastern', 'Marion Municipal Airport'),
('KDVT', 'US/Mountain', 'Phoenix Deer Valley Airport'),
('KCNC', 'US/Central', 'Chariton Municipal Airport'),
('KFFX', 'US/Eastern', 'Fremont Municipal Airport'),
('KIGM', 'US/Mountain', 'Kingman Airport'),
('KMGW', 'US/Eastern', 'Morgantown Municipal Airport Walter L. (Bill) Hart Field'),
('KMRJ', 'US/Central', 'Iowa County Airport'),
('KPVG', 'US/Eastern', 'Hampton Roads Executive Airport'),
('KCMA', 'US/Pacific', 'Camarillo International Airport'),
('KNFW', 'US/Central', 'NAS Fort Worth JRB / Carswell Field'),
('KSPA', 'US/Eastern', 'Spartanburg Downtown Memorial Airport'),
('KHWY', 'US/Eastern', 'Warrenton Fauquier Airport'),
('KPTB', 'US/Eastern', 'Dinwiddie County Airport'),
('KBTR', 'US/Central', 'Baton Rouge Metropolitan Airport'),
('KNTU', 'US/Eastern', 'Oceana Naval Air Station'),
('KCFE', 'US/Central', 'Buffalo Municipal Airport'),
('KNYG', 'US/Eastern', 'Quantico Marine Corps Airfield / Turner Field'),
('KAST', 'US/Pacific', 'Astoria Regional Airport'),
('KSYN', 'US/Central', 'Stanton Airfield'),
('KMCE', 'US/Pacific', 'Merced Regional Macready Field'),
('KPAO', 'US/Pacific', 'Palo Alto Airport'),
('KCBG', 'US/Central', 'Cambridge Municipal Airport'),
('KAFJ', 'US/Eastern', 'Washington County Airport'),
('KPWC', 'US/Central', 'Pine River Regional Airport'),
('KAKH', 'US/Eastern', 'Gastonia Municipal Airport'),
('KFYJ', 'US/Eastern', 'Middle Peninsula Regional Airport'),
('KETB', 'US/Central', 'West Bend Municipal Airport'),
('KCKB', 'US/Eastern', 'North Central West Virginia Airport'),
('KONO', 'US/Mountain', 'Ontario Municipal Airport'),
('KLOZ', 'US/Eastern', 'London-Corbin Airport/Magee Field'),
('KCEU', 'US/Eastern', 'Oconee County Regional Airport'),
('KMFR', 'US/Pacific', 'Rogue Valley International Medford Airport'),
('KPKB', 'US/Eastern', 'Mid Ohio Valley Regional Airport'),
('KBWG', 'US/Central', 'Bowling Green Warren County Regional Airport'),
('KCWA', 'US/Central', 'Central Wisconsin Airport'),
('KFET', 'US/Central', 'Fremont Municipal Airport'),
('KDAG', 'US/Pacific', 'Barstow Daggett Airport'),
('KCMI', 'US/Central', 'University of Illinois Willard Airport'),
('KFPK', 'US/Eastern', 'Fitch H Beach Airport'),
('KOQU', 'US/Eastern', 'Quonset State Airport'),
('KSBA', 'US/Pacific', 'Santa Barbara Municipal Airport'),
('KONP', 'US/Pacific', 'Newport Municipal Airport'),
('KMMH', 'US/Pacific', 'Mammoth Yosemite Airport'),
('KNRS', 'US/Pacific', 'Naval Outlying Field Imperial Beach (Ream Field)'),
('KSGU', 'US/Mountain', 'St George Regional Airport'),
('KLHM', 'US/Pacific', 'Lincoln Regional Karl Harder Field'),
('KTSP', 'US/Pacific', 'Tehachapi Municipal Airport'),
('KHLN', 'US/Mountain', 'Helena Regional Airport'),
('KGOK', 'US/Central', 'Guthrie-Edmond Regional Airport'),
('KRVS', 'US/Central', 'Tulsa Riverside Airport'),
('KHDC', 'US/Central', 'Hammond Northshore Regional Airport'),
('KNFL', 'US/Pacific', 'Fallon Naval Air Station'),
('K2G4', 'US/Eastern', 'Garrett County Airport'),
('KJST', 'US/Eastern', 'John Murtha Johnstown Cambria County Airport'),
('KBAZ', 'US/Central', 'New Braunfels Municipal Airport'),
('KSSF', 'US/Central', 'Stinson Municipal Airport'),
('KPEX', 'US/Central', 'Paynesville Municipal Airport'),
('KPNS', 'US/Central', 'Pensacola International Airport'),
('KLVM', 'US/Mountain', 'Mission Field'),
('KTNU', 'US/Central', 'Newton Municipal Airport'),
('KINT', 'US/Eastern', 'Smith Reynolds Airport'),
('KIAB', 'US/Central', 'McConnell Air Force Base'),
('KIYK', 'US/Pacific', 'Inyokern Airport'),
('KHCD', 'US/Central', 'Hutchinson Municipal Butler Field'),
('KIKK', 'US/Central', 'Greater Kankakee Airport'),
('KH21', 'US/Central', 'Camdenton Memorial Airport'),
('KHTS', 'US/Eastern', 'Tri-State Airport / Milton J. Ferguson Field'),
('KHNR', 'US/Central', 'Harlan Municipal Airport'),
('KJER', 'US/Mountain', 'Jerome County Airport'),
('KMRT', 'US/Eastern', 'Union County Airport'),
('KMGG', 'US/Central', 'Maple Lake Municipal Airport'),
('KGFL', 'US/Eastern', 'Floyd Bennett Memorial Airport'),
('KTQE', 'US/Central', 'Tekamah Municipal Airport'),
('KOEO', 'US/Central', 'L O Simenstad Municipal Airport'),
('KDWH', 'US/Central', 'David Wayne Hooks Memorial Airport'),
('KSTC', 'US/Central', 'Saint Cloud Regional Airport'),
('KHNZ', 'US/Eastern', 'Henderson Oxford Airport'),
('KTKI', 'US/Central', 'McKinney National Airport'),
('KVDF', 'US/Eastern', 'Tampa Executive Airport'),
('KWMC', 'US/Pacific', 'Winnemucca Municipal Airport'),
('KHQM', 'US/Pacific', 'Bowerman Airport'),
('KEGE', 'US/Mountain', 'Eagle County Regional Airport'),
('KMIW', 'US/Central', 'Marshalltown Municipal Airport'),
('KYNG', 'US/Eastern', 'Youngstown Warren Regional Airport'),
('KDDH', 'US/Eastern', 'William H Morse State Airport'),
('KSLE', 'US/Pacific', 'Salem-Willamette Valley Airport/McNary Field'),
('KAFW', 'US/Central', 'Perot Field/Fort Worth Alliance Airport'),
('KVOK', 'US/Central', 'Volk Field'),
('KONA', 'US/Central', 'Winona Municipal Airport Max Conrad Field'),
('KEAT', 'US/Pacific', 'Pangborn Memorial Airport'),
('KBJI', 'US/Central', 'Bemidji Regional Airport'),
('KBFD', 'US/Eastern', 'Bradford Regional Airport'),
('KJHW', 'US/Eastern', 'Chautauqua County-Jamestown Airport'),
('KFSD', 'US/Central', 'Sioux Falls Regional Airport / Joe Foss Field'),
('KEFT', 'US/Central', 'Monroe Municipal Airport'),
('KLXV', 'US/Mountain', 'Lake County Airport'),
('KCWI', 'US/Central', 'Clinton Municipal Airport'),
('KN03', 'US/Eastern', 'Cortland County Chase Field'),
('KWHP', 'US/Pacific', 'Whiteman Airport'),
('KROS', 'US/Central', 'Rush City Regional Airport'),
('KRPJ', 'US/Central', 'Rochelle Municipal Airport - Koritz Field'),
('KAXN', 'US/Central', 'Chandler Field'),
('KSBP', 'US/Pacific', 'San Luis County Regional Airport'),
('KSAV', 'US/Eastern', 'Savannah Hilton Head International Airport'),
('KMYL', 'US/Mountain', 'McCall Municipal Airport'),
('KEOK', 'US/Central', 'Keokuk Municipal Airport'),
('KCBE', 'US/Eastern', 'Greater Cumberland Regional Airport'),
('K6B0', 'US/Eastern', 'Middlebury State Airport'),
('KRQE', 'US/Mountain', 'Window Rock Airport'),
('KTCL', 'US/Central', 'Tuscaloosa National Airport'),
('KSMO', 'US/Pacific', 'Santa Monica Municipal Airport'),
('KIFA', 'US/Central', 'Iowa Falls Municipal Airport'),
('KUZA', 'US/Eastern', 'Rock Hill - York County Airport'),
('KBUY', 'US/Eastern', 'Burlington Alamance Regional Airport'),
('KRAC', 'US/Central', 'John H Batten Airport'),
('KASW', 'US/Eastern', 'Warsaw Municipal Airport'),
('KMUO', 'US/Mountain', 'Mountain Home Air Force Base'),
('KCXP', 'US/Pacific', 'Carson Airport'),
('KDNV', 'US/Central', 'Vermilion Regional Airport'),
('KITR', 'US/Mountain', 'Kit Carson County Airport'),
('KJAC', 'US/Mountain', 'Jackson Hole Airport'),
('KHBG', 'US/Central', 'Hattiesburg Bobby L Chain Municipal Airport'),
('KCNW', 'US/Central', 'TSTC Waco Airport'),
('K2W6', 'US/Eastern', 'St. Mary''s County Regional Airport'),
('KDEC', 'US/Central', 'Decatur Airport'),
('KMIV', 'US/Eastern', 'Millville Municipal Airport'),
('KBEH', 'US/Eastern', 'Southwest Michigan Regional Airport'),
('KORL', 'US/Eastern', 'Orlando Executive Airport'),
('KTTA', 'US/Eastern', 'Raleigh Executive Jetport'),
('KSFQ', 'US/Eastern', 'Suffolk Executive Airport'),
('KAIO', 'US/Central', 'Atlantic Municipal Airport'),
('KGRB', 'US/Central', 'Austin Straubel International Airport'),
('KHAI', 'US/Eastern', 'Three Rivers Municipal Dr Haines Airport'),
('KTOP', 'US/Central', 'Philip Billard Municipal Airport'),
('KCOQ', 'US/Central', 'Cloquet Carlton County Airport'),
('KDZJ', 'US/Eastern', 'Blairsville Airport'),
('KMSS', 'US/Eastern', 'Massena International Airport Richards Field'),
('KDOV', 'US/Eastern', 'Dover Air Force Base'),
('KCSV', 'US/Central', 'Crossville Memorial Airport Whitson Field'),
('KJEF', 'US/Central', 'Jefferson City Memorial Airport'),
('KWRI', 'US/Eastern', 'Mc Guire Air Force Base'),
('KBNL', 'US/Eastern', 'Barnwell Regional Airport'),
('KADU', 'US/Central', 'Audubon County Airport'),
('KSQI', 'US/Central', 'Whiteside County Airport - Joseph H Bittorf Field'),
('KJAN', 'US/Central', 'Jackson-Medgar Wiley Evers International Airport'),
('KY70', 'US/Eastern', 'Ionia County Airport'),
('KCTZ', 'US/Eastern', 'Sampson County Airport'),
('KEEO', 'US/Mountain', 'Meeker Airport'),
('KCSG', 'US/Eastern', 'Columbus Metropolitan Airport'),
('KOKZ', 'US/Eastern', 'Kaolin Field'),
('KTHA', 'US/Central', 'Tullahoma Regional Airport William Northern Field'),
('KPEO', 'US/Eastern', 'Penn Yan Airport'),
('KCTJ', 'US/Eastern', 'West Georgia Regional Airport / O V Gray Field'),
('KCFS', 'US/Eastern', 'Tuscola Area Airport'),
('KLEW', 'US/Eastern', 'Auburn Lewiston Municipal Airport'),
('KLNC', 'US/Central', 'Lancaster Airport'),
('KNUW', 'US/Pacific', 'Whidbey Island Naval Air Station (Ault Field)'),
('KNBC', 'US/Eastern', 'Beaufort MCAS - Merritt Field'),
('KLNK', 'US/Central', 'Lincoln Airport'),
('KVRB', 'US/Eastern', 'Vero Beach Regional Airport'),
('KCAG', 'US/Mountain', 'Craig Moffat Airport'),
('KLYV', 'US/Central', 'Quentin Aanenson Airfield - Luverne Municipal Airport'),
('KMCN', 'US/Eastern', 'Middle Georgia Regional Airport'),
('KDLH', 'US/Central', 'Duluth International Airport'),
('KHLG', 'US/Eastern', 'Wheeling Ohio County Airport'),
('KMCW', 'US/Central', 'Mason City Municipal Airport'),
('KSHR', 'US/Mountain', 'Sheridan County Airport'),
('KDYR', 'US/Central', 'Dyersburg Regional Airport'),
('KIWA', 'US/Mountain', 'Mesa Gateway Airport'),
('KHIF', 'US/Mountain', 'Hill Air Force Base'),
('KFCS', 'US/Mountain', 'Butts AAF (Fort Carson) Air Field'),
('KCIC', 'US/Pacific', 'Chico Regional Airport'),
('KFBG', 'US/Eastern', 'Simmons Army Air Field'),
('KDMA', 'US/Mountain', 'Davis Monthan Air Force Base'),
('KWST', 'US/Eastern', 'Westerly State Airport'),
('KDFI', 'US/Eastern', 'Defiance Memorial Airport'),
('KMUT', 'US/Central', 'Muscatine Municipal Airport'),
('KM16', 'US/Central', 'John Bell Williams Airport'),
('KGNV', 'US/Eastern', 'Gainesville Regional Airport'),
('KHHR', 'US/Pacific', 'Jack Northrop Field Hawthorne Municipal Airport'),
('KPUB', 'US/Mountain', 'Pueblo Memorial Airport'),
('KJWY', 'US/Central', 'Mid-Way Regional Airport'),
('KDKK', 'US/Eastern', 'Chautauqua County-Dunkirk Airport'),
('KHAF', 'US/Pacific', 'Half Moon Bay Airport'),
('KBHK', 'US/Mountain', 'Baker Municipal Airport'),
('KTOA', 'US/Pacific', 'Zamperini Field'),
('KLEB', 'US/Eastern', 'Lebanon Municipal Airport'),
('KBHM', 'US/Central', 'Birmingham-Shuttlesworth International Airport'),
('KXSA', 'US/Eastern', 'Tappahannock-Essex County Airport'),
('KGLR', 'US/Eastern', 'Gaylord Regional Airport'),
('KWJF', 'US/Pacific', 'General William J Fox Airfield'),
('K5C1', 'US/Central', 'Boerne Stage Field'),
('KSWO', 'US/Central', 'Stillwater Regional Airport'),
('KCPR', 'US/Mountain', 'Casper-Natrona County International Airport'),
('KSRE', 'US/Central', 'Seminole Municipal Airport'),
('KALN', 'US/Central', 'St Louis Regional Airport'),
('KCAV', 'US/Central', 'Clarion Municipal Airport'),
('KBDU', 'US/Mountain', 'Boulder Municipal Airport'),
('KLKV', 'US/Pacific', 'Lake County Airport'),
('KPUW', 'US/Pacific', 'Pullman-Moscow Regional Airport'),
('KMZH', 'US/Central', 'Moose Lake Carlton County Airport'),
('KBCK', 'US/Central', 'Black River Falls Area Airport'),
('KCAD', 'US/Eastern', 'Wexford County Airport'),
('KCUL', 'US/Central', 'Carmi Municipal Airport'),
('KCNI', 'US/Eastern', 'Cherokee County Regional Airport'),
('KLAR', 'US/Mountain', 'Laramie Regional Airport'),
('KC75', 'US/Central', 'Marshall County Airport'),
('KLRJ', 'US/Central', 'Le Mars Municipal Airport'),
('KGYH', 'US/Eastern', 'Donaldson Field Airport'),
('KBYG', 'US/Mountain', 'Johnson County Airport'),
('KLUM', 'US/Central', 'Menomonie Municipal Score Field'),
('KICL', 'US/Central', 'Schenck Field'),
('KLBF', 'US/Central', 'North Platte Regional Airport Lee Bird Field'),
('KSBN', 'US/Eastern', 'South Bend Regional Airport'),
('KRCM', 'US/Central', 'Skyhaven Airport'),
('KPNM', 'US/Central', 'Princeton Municipal Airport'),
('KDNN', 'US/Eastern', 'Dalton Municipal Airport'),
('KGNT', 'US/Mountain', 'Grants-Milan Municipal Airport'),
('KTWF', 'US/Mountain', 'Joslin Field Magic Valley Regional Airport'),
('KOMK', 'US/Pacific', 'Omak Airport'),
('KMJQ', 'US/Central', 'Jackson Municipal Airport'),
('KNEL', 'US/Eastern', 'Lakehurst Maxfield Field Airport'),
('KGCD', 'US/Pacific', 'Grant County Regional Airport / Ogilvie Field'),
('KVNY', 'US/Pacific', 'Van Nuys Airport'),
('KPMV', 'US/Central', 'Plattsmouth Municipal Airport'),
('KCAE', 'US/Eastern', 'Columbia Metropolitan Airport'),
('KAAO', 'US/Central', 'Colonel James Jabara Airport'),
('KLAX', 'US/Pacific', 'Los Angeles International Airport'),
('KWRB', 'US/Eastern', 'Robins Air Force Base'),
('KIAG', 'US/Eastern', 'Niagara Falls International Airport'),
('KLWS', 'US/Pacific', 'Lewiston Nez Perce County Airport'),
('KACB', 'US/Eastern', 'Antrim County Airport'),
('KDBQ', 'US/Central', 'Dubuque Regional Airport'),
('KNFG', 'US/Pacific', 'Camp Pendleton MCAS (Munn Field) Airport'),
('KOSA', 'US/Central', 'Mount Pleasant Regional Airport'),
('KBDN', 'US/Pacific', 'Bend Municipal Airport'),
('KPSC', 'US/Pacific', 'Tri Cities Airport'),
('KELP', 'US/Mountain', 'El Paso International Airport'),
('KSMS', 'US/Eastern', 'Sumter Airport'),
('KFMH', 'US/Eastern', 'Cape Cod Coast Guard Air Station'),
('KLIC', 'US/Mountain', 'Limon Municipal Airport'),
('KWVL', 'US/Eastern', 'Waterville Robert Lafleur Airport'),
('KCMY', 'US/Central', 'Sparta Fort McCoy Airport'),
('KEZS', 'US/Central', 'Shawano Municipal Airport'),
('KRBG', 'US/Pacific', 'Roseburg Regional Airport'),
('KSPB', 'US/Pacific', 'Scappoose Industrial Airpark'),
('KAFN', 'US/Eastern', 'Jaffrey Airfield Silver Ranch Airport'),
('KDMO', 'US/Central', 'Sedalia Memorial Airport'),
('KFYG', 'US/Central', 'Washington Regional Airport'),
('KNIP', 'US/Eastern', 'Jacksonville Naval Air Station (Towers Field)'),
('KMAE', 'US/Pacific', 'Madera Municipal Airport'),
('KHUM', 'US/Central', 'Houma Terrebonne Airport'),
('KPRC', 'US/Mountain', 'Prescott International Airport - Ernest A. Love Field'),
('KGMU', 'US/Eastern', 'Greenville Downtown Airport'),
('KGDJ', 'US/Central', 'Granbury Regional Airport'),
('K3LF', 'US/Central', 'Litchfield Municipal Airport'),
('KBFL', 'US/Pacific', 'Meadows Field'),
('KGJT', 'US/Mountain', 'Grand Junction Regional Airport'),
('KBMG', 'US/Eastern', 'Monroe County Airport'),
('KFDW', 'US/Eastern', 'Fairfield County Airport'),
('KBXK', 'US/Mountain', 'Buckeye Municipal Airport'),
('KGDB', 'US/Central', 'Granite Falls Municipal Airport / Lenzen-Roe Memorial Field'),
('KCYS', 'US/Mountain', 'Cheyenne Regional Jerry Olson Field'),
('KPUJ', 'US/Eastern', 'Silver Comet Field at Paulding Northwest Atlanta Airport'),
('KSBM', 'US/Central', 'Sheboygan County Memorial Airport'),
('KHJO', 'US/Pacific', 'Hanford Municipal Airport'),
('KFVX', 'US/Eastern', 'Farmville Regional Airport'),
('KTPF', 'US/Eastern', 'Peter O Knight Airport'),
('KMYV', 'US/Pacific', 'Yuba County Airport'),
('KEMV', 'US/Eastern', 'Emporia Greensville Regional Airport'),
('KMWH', 'US/Pacific', 'Grant County International Airport'),
('KUSE', 'US/Eastern', 'Fulton County Airport'),
('KAQW', 'US/Eastern', 'Harriman and West Airport'),
('KGGI', 'US/Central', 'Grinnell Regional Airport'),
('KCKV', 'US/Central', 'Clarksville–Montgomery County Regional Airport'),
('KDGW', 'US/Mountain', 'Converse County Airport'),
('KAMN', 'US/Eastern', 'Gratiot Community Airport'),
('KMOP', 'US/Eastern', 'Mount Pleasant Municipal Airport'),
('KCXO', 'US/Central', 'Conroe-North Houston Regional Airport'),
('KBCE', 'US/Mountain', 'Bryce Canyon Airport'),
('KOGB', 'US/Eastern', 'Orangeburg Municipal Airport'),
('KDLS', 'US/Pacific', 'Columbia Gorge Regional Airport'),
('KRBW', 'US/Eastern', 'Lowcountry Regional Airport'),
('KNQA', 'US/Central', 'Millington-Memphis Airport'),
('KMXF', 'US/Central', 'Maxwell Air Force Base'),
('KMWA', 'US/Central', 'Veterans Airport of Southern Illinois'),
('KSRQ', 'US/Eastern', 'Sarasota Bradenton International Airport'),
('KMOB', 'US/Central', 'Mobile Regional Airport'),
('KTKV', 'US/Central', 'Tomahawk Regional Airport'),
('KPTV', 'US/Pacific', 'Porterville Municipal Airport'),
('KRMG', 'US/Eastern', 'Richard B Russell Airport'),
('KTMA', 'US/Eastern', 'Henry Tift Myers Airport'),
('KMMV', 'US/Pacific', 'Mc Minnville Municipal Airport'),
('KFLO', 'US/Eastern', 'Florence Regional Airport'),
('KDYB', 'US/Eastern', 'Summerville Airport'),
('KISM', 'US/Eastern', 'Kissimmee Gateway Airport'),
('KDLN', 'US/Mountain', 'Dillon Airport'),
('KDTO', 'US/Central', 'Denton Enterprise Airport'),
('KFSO', 'US/Eastern', 'Franklin County State Airport'),
('KMYR', 'US/Eastern', 'Myrtle Beach International Airport'),
('K1V6', 'US/Mountain', 'Fremont County Airport'),
('KEUL', 'US/Mountain', 'Caldwell Executive Airport'),
('KTPL', 'US/Central', 'Draughon Miller Central Texas Regional Airport'),
('KSSC', 'US/Eastern', 'Shaw Air Force Base'),
('KOCQ', 'US/Central', 'J. Douglas Bake Memorial Airport'),
('KMTV', 'US/Eastern', 'Blue Ridge Airport'),
('KFST', 'US/Central', 'Fort Stockton Pecos County Airport'),
('KVEL', 'US/Mountain', 'Vernal Regional Airport'),
('KDAB', 'US/Eastern', 'Daytona Beach International Airport'),
('KBLF', 'US/Eastern', 'Mercer County Airport'),
('KMAO', 'US/Eastern', 'Marion County Airport'),
('KSBY', 'US/Eastern', 'Salisbury Ocean City Wicomico Regional Airport'),
('KWWD', 'US/Eastern', 'Cape May County Airport'),
('KJNX', 'US/Eastern', 'Johnston Regional Airport'),
('KSNL', 'US/Central', 'Shawnee Regional Airport'),
('KHVS', 'US/Eastern', 'Hartsville Regional Airport'),
('KWAL', 'US/Eastern', 'Wallops Flight Facility Airport'),
('K3J7', 'US/Eastern', 'Greene County Regional Airport'),
('KEHO', 'US/Eastern', 'Shelby-Cleveland County Regional Airport'),
('KBMI', 'US/Central', 'Central Illinois Regional Airport at Bloomington-Normal'),
('KCRE', 'US/Eastern', 'Grand Strand Airport'),
('KLKR', 'US/Eastern', 'Lancaster County-Mc Whirter Field'),
('KCKI', 'US/Eastern', 'Williamsburg Regional Airport'),
('KOTH', 'US/Pacific', 'Southwest Oregon Regional Airport'),
('KSKF', 'US/Central', 'Lackland Air Force Base'),
('KADC', 'US/Central', 'Wadena Municipal Airport'),
('KLFT', 'US/Central', 'Lafayette Regional Airport'),
('KFTG', 'US/Mountain', 'Colorado Air and Space Port'),
('KMPV', 'US/Eastern', 'Edward F Knapp State Airport'),
('KHYI', 'US/Central', 'San Marcos Regional Airport'),
('KHFF', 'US/Eastern', 'Mackall Army Air Field'),
('KMKS', 'US/Eastern', 'Berkeley County Airport'),
('KTRI', 'US/Eastern', 'Tri-Cities Regional TN/VA Airport'),
('KEET', 'US/Central', 'Shelby County Airport'),
('KLUX', 'US/Eastern', 'Laurens County Airport'),
('KCWC', 'US/Central', 'Kickapoo Downtown Airport'),
('KHUF', 'US/Eastern', 'Terre Haute Regional Airport, Hulman Field'),
('KMMT', 'US/Eastern', 'Mc Entire Joint National Guard Base'),
('KNLC', 'US/Pacific', 'Lemoore Naval Air Station (Reeves Field) Airport'),
('KVCV', 'US/Pacific', 'Southern California Logistics Airport'),
('KHRJ', 'US/Eastern', 'Harnett Regional Jetport Airport'),
('KSKA', 'US/Pacific', 'Fairchild Air Force Base'),
('KPIB', 'US/Central', 'Hattiesburg Laurel Regional Airport'),
('KAWM', 'US/Central', 'West Memphis Municipal Airport'),
('KDCM', 'US/Eastern', 'Chester Catawba Regional Airport'),
('KT65', 'US/Central', 'Mid Valley Airport'),
('KMTW', 'US/Central', 'Manitowoc County Airport'),
('KSVN', 'US/Eastern', 'Hunter Army Air Field'),
('KACV', 'US/Pacific', 'California Redwood Coast-Humboldt County Airport'),
('KCRQ', 'US/Pacific', 'McClellan-Palomar Airport'),
('KBKD', 'US/Central', 'Stephens County Airport'),
('KALX', 'US/Central', 'Thomas C Russell Field'),
('KM46', 'US/Mountain', 'Colstrip Airport'),
('KLQK', 'US/Eastern', 'Pickens County Airport'),
('KFOT', 'US/Pacific', 'Rohnerville Airport'),
('KIMT', 'US/Central', 'Ford Airport'),
('KMFI', 'US/Central', 'Marshfield Municipal Airport'),
('KTUL', 'US/Central', 'Tulsa International Airport'),
('KSHV', 'US/Central', 'Shreveport Regional Airport'),
('KCVO', 'US/Pacific', 'Corvallis Municipal Airport'),
('KMCO', 'US/Eastern', 'Orlando International Airport'),
('K5T6', 'US/Mountain', 'Doña Ana County International Jetport'),
('KBBP', 'US/Eastern', 'Marlboro County Jetport - H E Avent Field Airport'),
('KAMA', 'US/Central', 'Rick Husband Amarillo International Airport'),
('KBAD', 'US/Central', 'Barksdale Air Force Base'),
('KHNB', 'US/Eastern', 'Huntingburg Airport'),
('KPCZ', 'US/Central', 'Waupaca Municipal Airport'),
('KAEG', 'US/Mountain', 'Double Eagle II Airport'),
('KOWB', 'US/Central', 'Owensboro Daviess County Airport'),
('KHYW', 'US/Eastern', 'Conway Horry County Airport'),
('KCLI', 'US/Central', 'Clintonville Municipal Airport'),
('KCUB', 'US/Eastern', 'Jim Hamilton L.B. Owens Airport'),
('KMXO', 'US/Central', 'Monticello Regional Airport'),
('KLMO', 'US/Mountain', 'Vance Brand Airport'),
('KHLX', 'US/Eastern', 'Twin County Airport'),
('KBFM', 'US/Central', 'Mobile Downtown Airport'),
('KLRO', 'US/Eastern', 'Mount Pleasant Regional Airport Faison Field'),
('KRBL', 'US/Pacific', 'Red Bluff Municipal Airport'),
('KLXL', 'US/Central', 'Little Falls-Morrison County-Lindbergh field'),
('KISW', 'US/Central', 'Alexander Field South Wood County Airport'),
('KASE', 'US/Mountain', 'Aspen-Pitkin County Airport (Sardy Field)'),
('KEKA', 'US/Pacific', 'Murray Field'),
('KRDD', 'US/Pacific', 'Redding Municipal Airport'),
('KTDF', 'US/Eastern', 'Raleigh Regional Airport at Person County'),
('KPHF', 'US/Eastern', 'Newport News Williamsburg International Airport'),
('KLYH', 'US/Eastern', 'Lynchburg Regional Airport - Preston Glenn Field'),
('KMFV', 'US/Eastern', 'Accomack County Airport'),
('KEVV', 'US/Central', 'Evansville Regional Airport'),
('KAIT', 'US/Central', 'Aitkin Municipal Airport Steve Kurtz Field'),
('KCPC', 'US/Eastern', 'Columbus County Municipal Airport'),
('KMYF', 'US/Pacific', 'Montgomery-Gibbs Executive Airport'),
('KPPO', 'US/Central', 'La Porte Municipal Airport'),
('KMMI', 'US/Eastern', 'McMinn County Airport'),
('KRST', 'US/Central', 'Rochester International Airport'),
('KPRN', 'US/Central', 'Mac Crenshaw Memorial Airport'),
('KHIB', 'US/Central', 'Range Regional Airport'),
('KNGU', 'US/Eastern', 'Norfolk Naval Station (Chambers Field)'),
('KPVC', 'US/Eastern', 'Provincetown Municipal Airport'),
('KIDI', 'US/Eastern', 'Indiana County–Jimmy Stewart Airport'),
('KVLD', 'US/Eastern', 'Valdosta Regional Airport'),
('KY50', 'US/Central', 'Wautoma Municipal Airport'),
('KMRB', 'US/Eastern', 'Eastern WV Regional Airport/Shepherd Field'),
('KUKI', 'US/Pacific', 'Ukiah Municipal Airport'),
('KSSI', 'US/Eastern', 'St Simons Island Airport'),
('KFYV', 'US/Central', 'Drake Field'),
('KFSE', 'US/Central', 'Fosston Municipal Airport-Anderson Field'),
('KPEA', 'US/Central', 'Pella Municipal Airport'),
('KCTB', 'US/Mountain', 'Cut Bank International Airport'),
('KTTS', 'US/Eastern', 'Space Florida Launch and Landing Facility'),
('KENL', 'US/Central', 'Centralia Municipal Airport'),
('KFPR', 'US/Eastern', 'St Lucie County International Airport'),
('KFAY', 'US/Eastern', 'Fayetteville Regional Airport - Grannis Field'),
('KHKY', 'US/Eastern', 'Hickory Regional Airport'),
('KCDN', 'US/Eastern', 'Woodward Field'),
('KNPA', 'US/Central', 'Naval Air Station Pensacola Forrest Sherman Field'),
('KDMN', 'US/Mountain', 'Deming Municipal Airport'),
('KBOK', 'US/Pacific', 'Brookings Airport'),
('KPSK', 'US/Eastern', 'New River Valley Airport'),
('KJAX', 'US/Eastern', 'Jacksonville International Airport'),
('KMSO', 'US/Mountain', 'Missoula International Airport'),
('KCKP', 'US/Central', 'Cherokee County Regional Airport'),
('KIIB', 'US/Central', 'Independence Municipal Airport'),
('KBTM', 'US/Mountain', 'Bert Mooney Airport'),
('KOTM', 'US/Central', 'Ottumwa Regional Airport'),
('KLHZ', 'US/Eastern', 'Triangle North Executive Airport'),
('KY51', 'US/Central', 'Viroqua Municipal Airport'),
('KHUA', 'US/Central', 'Redstone Army Air Field'),
('KFAF', 'US/Eastern', 'Felker Army Air Field'),
('KOLV', 'US/Central', 'Olive Branch Airport'),
('KITH', 'US/Eastern', 'Ithaca Tompkins Regional Airport'),
('KSPG', 'US/Eastern', 'Albert Whitted Airport'),
('KFMM', 'US/Mountain', 'Fort Morgan Municipal Airport'),
('KBKE', 'US/Pacific', 'Baker City Municipal Airport'),
('KDEW', 'US/Pacific', 'Deer Park Airport'),
('KPBG', 'US/Eastern', 'Plattsburgh International Airport'),
('KTIX', 'US/Eastern', 'Space Coast Regional Airport'),
('KPIE', 'US/Eastern', 'St. Petersburg Clearwater International Airport'),
('KLCQ', 'US/Eastern', 'Lake City Gateway Airport'),
('KTPA', 'US/Eastern', 'Tampa International Airport'),
('KFMY', 'US/Eastern', 'Page Field'),
('KUUU', 'US/Eastern', 'Newport State Airport'),
('KOSH', 'US/Central', 'Wittman Regional Airport'),
('KCQX', 'US/Eastern', 'Chatham Municipal Airport'),
('KUTA', 'US/Central', 'Tunica Municipal Airport'),
('KGBN', 'US/Mountain', 'Gila Bend Air Force Auxiliary Airport'),
('KLWC', 'US/Central', 'Lawrence Municipal Airport'),
('KMWO', 'US/Eastern', 'Middletown Regional Airport'),
('KDYA', 'US/Central', 'Demopolis Municipal Airport'),
('KRZN', 'US/Central', 'Burnett County Airport'),
('KFLD', 'US/Central', 'Fond du Lac County Airport'),
('KEVW', 'US/Mountain', 'Evanston-Uinta County Airport-Burns Field'),
('KINF', 'US/Eastern', 'Inverness Airport'),
('KAWG', 'US/Central', 'Washington Municipal Airport'),
('KLFK', 'US/Central', 'Angelina County Airport'),
('KRZR', 'US/Eastern', 'Cleveland Regional Jetport'),
('KBMT', 'US/Central', 'Beaumont Municipal Airport'),
('KART', 'US/Eastern', 'Watertown International Airport'),
('KJYM', 'US/Eastern', 'Hillsdale Municipal Airport'),
('KBIX', 'US/Central', 'Keesler Air Force Base'),
('KHXD', 'US/Eastern', 'Hilton Head Airport'),
('KSOP', 'US/Eastern', 'Moore County Airport'),
('KGGE', 'US/Eastern', 'Georgetown County Airport'),
('KVPZ', 'US/Central', 'Porter County Municipal Airport'),
('KIXA', 'US/Eastern', 'Halifax-Northampton Regional Airport'),
('KAKQ', 'US/Eastern', 'Wakefield Municipal Airport'),
('KEPH', 'US/Pacific', 'Ephrata Municipal Airport'),
('KPBF', 'US/Central', 'Pine Bluff Regional Airport, Grider Field'),
('KVQQ', 'US/Eastern', 'Cecil Airport'),
('KCQW', 'US/Eastern', 'Cheraw Municipal Airport/Lynch Bellinger Field'),
('KCWF', 'US/Central', 'Chennault International Airport'),
('KACQ', 'US/Central', 'Waseca Municipal Airport'),
('KLWV', 'US/Central', 'Lawrenceville Vincennes International Airport'),
('KJFZ', 'US/Eastern', 'Tazewell County Airport'),
('KCLL', 'US/Central', 'Easterwood Field'),
('KBCT', 'US/Eastern', 'Boca Raton Airport'),
('KSAZ', 'US/Central', 'Staples Municipal Airport'),
('KHYA', 'US/Eastern', 'Cape Cod Gateway Airport'),
('KBIH', 'US/Pacific', 'Eastern Sierra Regional Airport'),
('K1H2', 'US/Central', 'Effingham County Memorial Airport'),
('KMRC', 'US/Central', 'Maury County Airport'),
('KVSF', 'US/Eastern', 'Hartness State Airport'),
('KZPH', 'US/Eastern', 'Zephyrhills Municipal Airport'),
('KRDK', 'US/Central', 'Red Oak Municipal Airport'),
('KOXR', 'US/Pacific', 'Oxnard Airport'),
('KEFK', 'US/Eastern', 'Northeast Kingdom International Airport'),
('KDTN', 'US/Central', 'Shreveport Downtown Airport'),
('K6R3', 'US/Central', 'Cleveland Municipal Airport'),
('KFFZ', 'US/Mountain', 'Falcon Field'),
('KMGC', 'US/Central', 'Michigan City Municipal Airport'),
('KLAA', 'US/Mountain', 'Southeast Colorado Regional Airport'),
('KCQM', 'US/Central', 'Cook Municipal Airport'),
('KNXP', 'US/Pacific', 'Twentynine Palms Strategic Expeditionary Landing Field'),
('KP08', 'US/Mountain', 'Coolidge Municipal Airport'),
('KCJR', 'US/Eastern', 'Culpeper Regional Airport'),
('KFKL', 'US/Eastern', 'Venango Regional Airport'),
('KVDI', 'US/Eastern', 'Vidalia Regional Airport'),
('KILM', 'US/Eastern', 'Wilmington International Airport'),
('KPAM', 'US/Central', 'Tyndall Air Force Base'),
('KOGS', 'US/Eastern', 'Ogdensburg International Airport'),
('KGGG', 'US/Central', 'East Texas Regional Airport'),
('KRIL', 'US/Mountain', 'Garfield County Regional Airport'),
('KHQU', 'US/Eastern', 'Thomson-McDuffie County Airport'),
('KVKS', 'US/Central', 'Vicksburg Municipal Airport'),
('KBHB', 'US/Eastern', 'Hancock County-Bar Harbor Airport'),
('KELY', 'US/Pacific', 'Ely Airport Yelland Field'),
('KSAF', 'US/Mountain', 'Santa Fe Municipal Airport'),
('KDPG', 'US/Mountain', 'Michael AAF (Dugway Proving Ground) Airport'),
('KBNW', 'US/Central', 'Boone Municipal Airport'),
('KGBG', 'US/Central', 'Galesburg Municipal Airport'),
('KUOX', 'US/Central', 'University Oxford Airport'),
('KARW', 'US/Eastern', 'Beaufort Executive Airport'),
('KGXY', 'US/Mountain', 'Greeley–Weld County Airport'),
('KGPT', 'US/Central', 'Gulfport Biloxi International Airport'),
('KRYN', 'US/Mountain', 'Ryan Field'),
('KGGP', 'US/Eastern', 'Logansport Cass County Airport'),
('KCDC', 'US/Mountain', 'Cedar City Regional Airport'),
('KSRB', 'US/Central', 'Upper Cumberland Regional Airport'),
('KBYI', 'US/Mountain', 'Burley Municipal Airport'),
('KCRG', 'US/Eastern', 'Jacksonville Executive at Craig Airport'),
('KGYL', 'US/Central', 'Glencoe Municipal Airport'),
('KUDG', 'US/Eastern', 'Darlington County Airport'),
('KLRD', 'US/Central', 'Laredo International Airport'),
('KNBJ', 'US/Central', 'Naval Outlying Field Barin'),
('KMHV', 'US/Pacific', 'Mojave Airport'),
('KLRU', 'US/Mountain', 'Las Cruces International Airport'),
('KSAR', 'US/Central', 'Sparta Community Airport - Hunter Field'),
('KLHW', 'US/Eastern', 'MidCoast Regional Airport at Wright Army Airfield'),
('KAJO', 'US/Pacific', 'Corona Municipal Airport'),
('KHKA', 'US/Central', 'Blytheville Municipal Airport'),
('KICT', 'US/Central', 'Wichita Eisenhower National Airport'),
('KFQD', 'US/Eastern', 'Rutherford County Marchman Field'),
('KGLS', 'US/Central', 'Scholes International At Galveston Airport'),
('KBMC', 'US/Mountain', 'Brigham City Regional Airport'),
('KASD', 'US/Central', 'Slidell Airport'),
('KRUT', 'US/Eastern', 'Rutland - Southern Vermont Regional Airport'),
('KGED', 'US/Eastern', 'Delaware Coastal Airport'),
('KOMN', 'US/Eastern', 'Ormond Beach Municipal Airport'),
('KGYR', 'US/Mountain', 'Phoenix Goodyear Airport'),
('KCEW', 'US/Central', 'Bob Sikes Airport'),
('K04W', 'US/Central', 'Field of Dreams Airport'),
('KUCY', 'US/Central', 'Everett-Stewart Regional Airport'),
('K54J', 'US/Central', 'Defuniak Springs Airport'),
('KOKK', 'US/Central', 'Kokomo Municipal Airport'),
('KSFB', 'US/Eastern', 'Orlando Sanford International Airport'),
('KIWI', 'US/Eastern', 'Wiscasset Airport'),
('KDED', 'US/Eastern', 'Deland Municipal Sidney H Taylor Field'),
('KCPK', 'US/Eastern', 'Chesapeake Regional Airport'),
('KMNI', 'US/Eastern', 'Santee Cooper Regional Airport'),
('KRCE', 'US/Central', 'Clarence E Page Municipal Airport'),
('KGAD', 'US/Central', 'Northeast Alabama Regional Airport'),
('KMDQ', 'US/Central', 'Madison County Executive Airport-Tom Sharp Jr Field'),
('KTOI', 'US/Central', 'Troy Municipal Airport at N Kenneth Campbell Field'),
('KGEU', 'US/Mountain', 'Glendale Municipal Airport'),
('KVWU', 'US/Central', 'Waskish Municipal Airport'),
('KBOW', 'US/Eastern', 'Bartow Executive Airport'),
('KPKD', 'US/Central', 'Park Rapids Municipal Airport Konshok Field'),
('KLWD', 'US/Central', 'Lamoni Municipal Airport'),
('KOPF', 'US/Eastern', 'Miami-Opa Locka Executive Airport'),
('KPRB', 'US/Pacific', 'Paso Robles Municipal Airport'),
('KGTB', 'US/Eastern', 'Wheeler Sack Army Air Field'),
('K42J', 'US/Eastern', 'Keystone Heights Airport'),
('KRGK', 'US/Central', 'Red Wing Regional Airport'),
('KGUS', 'US/Eastern', 'Grissom Air Reserve Base'),
('KRUE', 'US/Central', 'Russellville Regional Airport'),
('KTLH', 'US/Eastern', 'Tallahassee Regional Airport'),
('KHFJ', 'US/Central', 'Monett Regional Airport'),
('KEFD', 'US/Central', 'Ellington Airport'),
('KLHX', 'US/Mountain', 'La Junta Municipal Airport'),
('KOCF', 'US/Eastern', 'Ocala International Airport - Jim Taylor Field'),
('KJGG', 'US/Eastern', 'Williamsburg Jamestown Airport'),
('KAKO', 'US/Mountain', 'Colorado Plains Regional Airport'),
('KLIT', 'US/Central', 'Bill & Hillary Clinton National Airport/Adams Field'),
('KSNK', 'US/Central', 'Winston Field'),
('KDVP', 'US/Central', 'Slayton Municipal Airport'),
('KHWO', 'US/Eastern', 'North Perry Airport'),
('KMML', 'US/Central', 'Southwest Minnesota Regional Airport - Marshall/Ryan Field'),
('KSGT', 'US/Central', 'Stuttgart Municipal Airport / Carl Humphrey Field'),
('KM30', 'US/Central', 'Metropolis Municipal Airport'),
('K8A0', 'US/Central', 'Albertville Regional Airport/Thomas J Brumlik Field'),
('KHSV', 'US/Central', 'Huntsville International Carl T Jones Field'),
('KLBX', 'US/Central', 'Texas Gulf Coast Regional Airport'),
('KMIA', 'US/Eastern', 'Miami International Airport'),
('KBZN', 'US/Mountain', 'Bozeman Yellowstone International Airport'),
('KLVS', 'US/Mountain', 'Las Vegas Municipal Airport'),
('KOWA', 'US/Central', 'Owatonna Degner Regional Airport'),
('KRQB', 'US/Eastern', 'Roben Hood Airport'),
('KHIE', 'US/Eastern', 'Mount Washington Regional Airport'),
('KFUL', 'US/Pacific', 'Fullerton Municipal Airport'),
('KOXB', 'US/Eastern', 'Ocean City Municipal Airport'),
('KRKS', 'US/Mountain', 'Southwest Wyoming Regional Airport'),
('KFSK', 'US/Central', 'Fort Scott Municipal Airport'),
('KCQF', 'US/Central', 'H L Sonny Callahan Airport'),
('KRWL', 'US/Mountain', 'Rawlins Municipal Airport/Harvey Field'),
('KCNY', 'US/Mountain', 'Canyonlands Regional Airport'),
('K4A9', 'US/Central', 'Isbell Field'),
('KJYL', 'US/Eastern', 'Plantation Airpark'),
('KMAI', 'US/Central', 'Marianna Municipal Airport'),
('KLKU', 'US/Eastern', 'Louisa County Airport / Freeman Field'),
('KTCC', 'US/Mountain', 'Tucumcari Municipal Airport'),
('KMRY', 'US/Pacific', 'Monterey Peninsula Airport'),
('KBYH', 'US/Central', 'Arkansas International Airport'),
('KGVT', 'US/Central', 'Majors Airport'),
('KRSW', 'US/Eastern', 'Southwest Florida International Airport'),
('KPGD', 'US/Eastern', 'Punta Gorda Airport'),
('KGTU', 'US/Central', 'Georgetown Executive Airport at Johnny Gantt Field'),
('KC35', 'US/Central', 'Reedsburg Municipal Airport'),
('KENV', 'US/Mountain', 'Wendover Airport'),
('KHTL', 'US/Eastern', 'Roscommon County - Blodgett Memorial Airport'),
('KBRD', 'US/Central', 'Brainerd Lakes Regional Airport'),
('KDBN', 'US/Eastern', 'W H ''Bud'' Barron Airport'),
('KVAD', 'US/Eastern', 'Moody Air Force Base'),
('KFXE', 'US/Eastern', 'Fort Lauderdale Executive Airport'),
('KULM', 'US/Central', 'New Ulm Municipal Airport'),
('KCMX', 'US/Eastern', 'Houghton County Memorial Airport'),
('KOWP', 'US/Central', 'William R. Pogue Municipal Airport'),
('KANB', 'US/Central', 'Anniston Regional Airport'),
('KOLU', 'US/Central', 'Columbus Municipal Airport'),
('KVER', 'US/Central', 'Jesse Viertel Memorial Airport'),
('KBVU', 'US/Pacific', 'Boulder City Municipal Airport'),
('KBTV', 'US/Eastern', 'Burlington International Airport'),
('KHRT', 'US/Central', 'Hurlburt Field'),
('KPBI', 'US/Eastern', 'Palm Beach International Airport'),
('KNMM', 'US/Central', 'Naval Air Station Meridian / McCain Field'),
('KSNY', 'US/Mountain', 'Sidney Municipal Airport Lloyd W Carr Field'),
('KBGD', 'US/Central', 'Hutchinson County Airport'),
('KBGF', 'US/Eastern', 'Winchester Municipal Airport'),
('KLGU', 'US/Mountain', 'Logan-Cache Airport'),
('KTCS', 'US/Mountain', 'Truth or Consequences Municipal Airport'),
('KPCM', 'US/Eastern', 'Plant City Municipal Airport'),
('KMFE', 'US/Central', 'McAllen Miller International Airport'),
('KJLN', 'US/Central', 'Joplin Regional Airport'),
('KJZI', 'US/Eastern', 'Charleston Executive Airport'),
('KTAD', 'US/Mountain', 'Perry Stokes Airport'),
('KLOL', 'US/Pacific', 'Derby Field'),
('KRWI', 'US/Eastern', 'Rocky Mount Wilson Regional Airport'),
('KLRF', 'US/Central', 'Little Rock Air Force Base'),
('KYKM', 'US/Pacific', 'Yakima Air Terminal McAllister Field'),
('KMGM', 'US/Central', 'Montgomery Regional (Dannelly Field) Airport'),
('KMLS', 'US/Mountain', 'Miles City Airport - Frank Wiley Field'),
('KDYT', 'US/Central', 'Sky Harbor Airport'),
('KDTL', 'US/Central', 'Detroit Lakes Airport'),
('KGWW', 'US/Eastern', 'Wayne Executive Jetport'),
('KTOC', 'US/Eastern', 'Toccoa Airport - R.G. Letourneau Field'),
('KJYG', 'US/Central', 'St James Municipal Airport'),
('KUXL', 'US/Central', 'Southland Field'),
('KMSL', 'US/Central', 'Northwest Alabama Regional Airport'),
('KRHI', 'US/Central', 'Rhinelander Oneida County Airport'),
('KGUP', 'US/Mountain', 'Gallup Municipal Airport'),
('KOLE', 'US/Eastern', 'Cattaraugus County-Olean Airport'),
('KANK', 'US/Mountain', 'Salida Airport - Harriet Alexander Field'),
('KFRM', 'US/Central', 'Fairmont Municipal Airport'),
('KLPC', 'US/Pacific', 'Lompoc Airport'),
('KCKF', 'US/Eastern', 'Crisp County Cordele Airport'),
('KODO', 'US/Central', 'Odessa Schlemeyer Field'),
('KLNR', 'US/Central', 'Tri-County Regional Airport'),
('KAUM', 'US/Central', 'Austin Municipal Airport'),
('KFLL', 'US/Eastern', 'Fort Lauderdale Hollywood International Airport'),
('KMLJ', 'US/Eastern', 'Baldwin County Regional Airport'),
('KLVJ', 'US/Central', 'Pearland Regional Airport'),
('KCGZ', 'US/Mountain', 'Casa Grande Municipal Airport'),
('KSBO', 'US/Eastern', 'Emanuel County Airport'),
('KSPS', 'US/Central', 'Wichita Falls Municipal Airport / Sheppard Air Force Base'),
('KSLI', 'US/Pacific', 'Los Alamitos Army Air Field'),
('KMEB', 'US/Eastern', 'Laurinburg Maxton Airport'),
('KRUQ', 'US/Eastern', 'Mid-Carolina Regional Airport'),
('KHJH', 'US/Central', 'Hebron Municipal Airport'),
('KGDV', 'US/Mountain', 'Dawson Community Airport'),
('KINL', 'US/Central', 'Falls International Airport'),
('KECP', 'US/Eastern', 'Northwest Florida Beaches International Airport'),
('KMLU', 'US/Central', 'Monroe Regional Airport'),
('KLUF', 'US/Mountain', 'Luke Air Force Base'),
('KM19', 'US/Central', 'Newport Regional Airport'),
('KRSN', 'US/Central', 'Ruston Regional Airport'),
('KHDN', 'US/Mountain', 'Yampa Valley Airport'),
('KNKX', 'US/Pacific', 'Miramar Marine Corps Air Station - Mitscher Field'),
('KAZC', 'US/Mountain', 'Colorado City Municipal Airport'),
('KFTK', 'US/Eastern', 'Godman Army Air Field'),
('KFLY', 'US/Mountain', 'Meadow Lake Airport'),
('KEXX', 'US/Eastern', 'Davidson County Executive Airport'),
('K3R7', 'US/Central', 'Jennings Airport'),
('KDHN', 'US/Central', 'Dothan Regional Airport'),
('KIZA', 'US/Pacific', 'Santa Ynez Airport'),
('KRWF', 'US/Central', 'Redwood Falls Municipal Airport'),
('KAPF', 'US/Eastern', 'Naples Municipal Airport'),
('KPQL', 'US/Central', 'Trent Lott International Airport'),
('KSAN', 'US/Pacific', 'San Diego International Airport'),
('KMCF', 'US/Eastern', 'MacDill Air Force Base'),
('KLAL', 'US/Eastern', 'Lakeland Linder International Airport'),
('KSAD', 'US/Mountain', 'Safford Regional Airport'),
('KSDL', 'US/Mountain', 'Scottsdale Airport'),
('KO86', 'US/Pacific', 'Trinity Center Airport'),
('KNRB', 'US/Eastern', 'Naval Station Mayport / Admiral David L McDonald Field'),
('KEDW', 'US/Pacific', 'Edwards Air Force Base'),
('KTMB', 'US/Eastern', 'Miami Executive Airport'),
('KLGC', 'US/Eastern', 'LaGrange Callaway Airport'),
('KCGC', 'US/Eastern', 'Crystal River Airport'),
('KAQP', 'US/Central', 'Appleton Municipal Airport'),
('KSUA', 'US/Eastern', 'Witham Field'),
('KCNO', 'US/Pacific', 'Chino Airport'),
('KPMP', 'US/Eastern', 'Pompano Beach Airpark'),
('KSMX', 'US/Pacific', 'Santa Maria Public Airport Captain G Allan Hancock Field'),
('K40J', 'US/Eastern', 'Perry-Foley Airport'),
('KSBS', 'US/Mountain', 'Steamboat Springs Bob Adams Field'),
('KEED', 'US/Pacific', 'Needles Airport'),
('K1M4', 'US/Central', 'Posey Field'),
('KAJZ', 'US/Mountain', 'Blake Field'),
('KNCA', 'US/Eastern', 'MCAS New River / McCutcheon Field'),
('K12N', 'US/Eastern', 'Aeroflex-Andover Airport'),
('KLWT', 'US/Mountain', 'Lewistown Municipal Airport'),
('KCOF', 'US/Eastern', 'Patrick Space Force Base'),
('KFZG', 'US/Eastern', 'Fitzgerald Municipal Airport'),
('KGIF', 'US/Eastern', 'Winter Haven Regional Airport - Gilbert Field'),
('KCEC', 'US/Pacific', 'Jack Mc Namara Field Airport'),
('KAUO', 'US/Central', 'Auburn University Regional Airport'),
('KELZ', 'US/Eastern', 'Wellsville Municipal Airport - Tarantine Field'),
('KTUP', 'US/Central', 'Tupelo Regional Airport'),
('KGZH', 'US/Central', 'Evergreen Regional Airport/Middleton Field'),
('KNZY', 'US/Pacific', 'North Island Naval Air Station-Halsey Field'),
('KMVN', 'US/Central', 'Mount Vernon Outland Airport'),
('KIER', 'US/Central', 'Natchitoches Regional Airport'),
('KUIL', 'US/Pacific', 'Quillayute Airport'),
('KHEY', 'US/Central', 'Hanchey Army (Fort Rucker) Heliport'),
('KFHB', 'US/Eastern', 'Fernandina Beach Municipal Airport'),
('KUKF', 'US/Eastern', 'Wilkes County Airport'),
('KACJ', 'US/Eastern', 'Jimmy Carter Regional Airport'),
('KSEE', 'US/Pacific', 'Gillespie Field'),
('KFFM', 'US/Central', 'Fergus Falls Municipal Airport - Einar Mickelson Field'),
('KHOT', 'US/Central', 'Memorial Field Airport'),
('KJMR', 'US/Central', 'Mora Municipal Airport'),
('KSDM', 'US/Pacific', 'Brown Field Municipal Airport'),
('KGSB', 'US/Eastern', 'Seymour Johnson Air Force Base'),
('KXVG', 'US/Central', 'Longville Municipal Airport'),
('K1A5', 'US/Eastern', 'Macon County Airport'),
('KHST', 'US/Eastern', 'Homestead ARB Airport'),
('KUTS', 'US/Central', 'Huntsville Regional Airport'),
('KHSA', 'US/Central', 'Stennis International Airport'),
('KDTS', 'US/Central', 'Destin Executive Airport'),
('KMTH', 'US/Eastern', 'The Florida Keys Marathon Airport'),
('KNYL', 'US/Mountain', 'Yuma International Airport / Marine Corps Air Station Yuma'),
('KO54', 'US/Pacific', 'Lonnie Pool Field Weaverville Airport'),
('KHBI', 'US/Eastern', 'Asheboro Regional Airport'),
('KTPH', 'US/Pacific', 'Tonopah Airport'),
('KFAM', 'US/Central', 'Farmington Regional Airport'),
('KMEI', 'US/Central', 'Key Field / Meridian Regional Airport'),
('KTVI', 'US/Eastern', 'Thomasville Regional Airport'),
('KOVL', 'US/Central', 'Olivia Regional Airport'),
('KLOR', 'US/Central', 'Lowe AHP (Fort Rucker) Heliport'),
('KMRN', 'US/Eastern', 'Foothills Regional Airport'),
('KETC', 'US/Eastern', 'Tarboro Edgecombe Airport'),
('KELD', 'US/Central', 'South Arkansas Regional Airport at Goodwin Field'),
('K9A4', 'US/Central', 'Courtland Airport'),
('KEVB', 'US/Eastern', 'New Smyrna Beach Municipal Airport'),
('KGCN', 'US/Mountain', 'Grand Canyon National Park Airport'),
('KBLH', 'US/Pacific', 'Blythe Airport'),
('KEWN', 'US/Eastern', 'Coastal Carolina Regional Airport'),
('KSLK', 'US/Eastern', 'Adirondack Regional Airport'),
('KRHP', 'US/Eastern', 'Western Carolina Regional Airport'),
('KNSE', 'US/Central', 'Whiting Field Naval Air Station - North'),
('K4A6', 'US/Central', 'Scottsboro Municipal Word Field'),
('KVBT', 'US/Central', 'Bentonville Municipal-Louise M Thaden Field'),
('KNID', 'US/Pacific', 'China Lake Naws (Armitage Field) Airport'),
('KVPS', 'US/Central', 'Destin-Fort Walton Beach Airport'),
('KISO', 'US/Eastern', 'Kinston Regional Jetport At Stallings Field'),
('KOCW', 'US/Eastern', 'Warren Field'),
('KDRO', 'US/Mountain', 'Durango La Plata County Airport'),
('KOMH', 'US/Eastern', 'Orange County Airport'),
('KJBR', 'US/Central', 'Jonesboro Municipal Airport'),
('KLSF', 'US/Eastern', 'Lawson Army Air Field'),
('KBQK', 'US/Eastern', 'Brunswick Golden Isles Airport'),
('KTBR', 'US/Eastern', 'Statesboro Bulloch County Airport'),
('KNBG', 'US/Central', 'New Orleans NAS JRB/Alvin Callender Field'),
('KOAJ', 'US/Eastern', 'Albert J Ellis Airport'),
('KLNP', 'US/Eastern', 'Lonesome Pine Airport'),
('K14Y', 'US/Central', 'Todd Field'),
('KCTY', 'US/Eastern', 'Cross City Airport'),
('KCWV', 'US/Eastern', 'Claxton Evans County Airport'),
('KPNT', 'US/Central', 'Pontiac Municipal Airport'),
('KGPI', 'US/Mountain', 'Glacier Park International Airport'),
('KNDZ', 'US/Central', 'Whiting Field Naval Air Station South Airport'),
('KJFX', 'US/Central', 'Walker County Airport Bevill Field'),
('KCIR', 'US/Central', 'Cairo Regional Airport'),
('KELO', 'US/Central', 'Ely Municipal Airport'),
('KDRA', 'US/Pacific', 'Desert Rock Airport'),
('KPGA', 'US/Mountain', 'Page Municipal Airport'),
('KTKC', 'US/Central', 'Tracy Municipal Airport'),
('KIFP', 'US/Mountain', 'Laughlin Bullhead International Airport'),
('K33V', 'US/Mountain', 'Walden Jackson County Airport'),
('KSRC', 'US/Central', 'Searcy Municipal Airport'),
('KASJ', 'US/Eastern', 'Tri-County Airport at Henry Joyner Field'),
('KFSM', 'US/Central', 'Fort Smith Regional Airport'),
('KTVC', 'US/Eastern', 'Cherry Capital Airport'),
('KLLQ', 'US/Central', 'Monticello Municipal Ellis Field'),
('KIJX', 'US/Central', 'Jacksonville Municipal Airport'),
('KNFE', 'US/Eastern', 'Fentress Naval Auxiliary Landing Field'),
('KFEP', 'US/Central', 'Albertus Airport'),
('KTRL', 'US/Central', 'Terrell Municipal Airport'),
('KFAR', 'US/Central', 'Hector International Airport'),
('KMWK', 'US/Eastern', 'Mount Airy Surry County Airport'),
('KIPJ', 'US/Eastern', 'Lincolnton Lincoln County Regional Airport'),
('KFOD', 'US/Central', 'Fort Dodge Regional Airport'),
('KOOA', 'US/Central', 'Oskaloosa Municipal Airport'),
('KPLN', 'US/Eastern', 'Pellston Regional Airport of Emmet County Airport'),
('KSIF', 'US/Eastern', 'Rockingham County NC Shiloh Airport'),
('KHVR', 'US/Mountain', 'Havre City County Airport'),
('KROG', 'US/Central', 'Rogers Municipal Airport-Carter Field'),
('KVCT', 'US/Central', 'Victoria Regional Airport'),
('K65S', 'US/Pacific', 'Boundary County Airport'),
('KAAT', 'US/Pacific', 'Alturas Municipal Airport'),
('KHOP', 'US/Central', 'Campbell Army Airfield (Fort Campbell)'),
('KSIY', 'US/Pacific', 'Siskiyou County Airport'),
('KJMS', 'US/Central', 'Jamestown Regional Airport'),
('KMKY', 'US/Eastern', 'Marco Island Executive Airport'),
('KSTK', 'US/Mountain', 'Sterling Municipal Airport'),
('KGHW', 'US/Central', 'Glenwood Municipal Airport'),
('KABY', 'US/Eastern', 'Southwest Georgia Regional Airport'),
('KXMR', 'US/Eastern', 'Cape Canaveral SFS Skid Strip'),
('KAEX', 'US/Central', 'Alexandria International Airport'),
('KEZM', 'US/Eastern', 'Heart of Georgia Regional Airport'),
('KSUT', 'US/Eastern', 'Cape Fear Regional Jetport / Howie Franklin Field Airport'),
('KBIS', 'US/Central', 'Bismarck Municipal Airport'),
('KHOE', 'US/Eastern', 'Homerville Airport'),
('K79J', 'US/Central', 'South Alabama Regional At Bill Benton Field Airport'),
('KTXK', 'US/Central', 'Texarkana Regional Airport (Webb Field)'),
('KM89', 'US/Central', 'Dexter B Florence Memorial Field'),
('K20V', 'US/Mountain', 'McElroy Airfield'),
('KJKJ', 'US/Central', 'Moorhead Municipal Airport'),
('KGFK', 'US/Central', 'Grand Forks International Airport'),
('KCEZ', 'US/Mountain', 'Cortez Municipal Airport'),
('KSJN', 'US/Mountain', 'St Johns Industrial Air Park'),
('KORB', 'US/Central', 'Orr Regional Airport'),
('K6A1', 'US/Eastern', 'Butler Municipal Airport'),
('KMEZ', 'US/Central', 'Mena Intermountain Municipal Airport'),
('KBBB', 'US/Central', 'Benson Municipal Airport'),
('KTVF', 'US/Central', 'Thief River Falls Regional Airport'),
('KRCZ', 'US/Eastern', 'Richmond County Airport'),
('KPGV', 'US/Eastern', 'Pitt-Greenville Airport'),
('KNQX', 'US/Eastern', 'Naval Air Station Key West/Boca Chica Field'),
('KFHU', 'US/Mountain', 'Sierra Vista Municipal Airport / Libby Army Air Field'),
('KASG', 'US/Central', 'Springdale Municipal Airport'),
('KEYF', 'US/Eastern', 'Curtis L Brown Jr Field'),
('KMOT', 'US/Central', 'Minot International Airport'),
('KDPL', 'US/Eastern', 'Duplin County Airport'),
('KY19', 'US/Central', 'Mandan Municipal Airport'),
('KLBT', 'US/Eastern', 'Lumberton Regional Airport'),
('KDEQ', 'US/Central', 'J Lynn Helms Sevier County Airport'),
('KW22', 'US/Eastern', 'Upshur County Regional Airport'),
('KCDH', 'US/Central', 'Harrell Field'),
('KSLG', 'US/Central', 'Smith Field'),
('KEUF', 'US/Central', 'Weedon Field'),
('KNUI', 'US/Eastern', 'Naval Outlying Landing Field Webster'),
('KMTJ', 'US/Mountain', 'Montrose Regional Airport'),
('KHRX', 'US/Central', 'Hereford Municipal Airport'),
('KUBE', 'US/Central', 'Cumberland Municipal Airport'),
('KCCA', 'US/Central', 'Clinton Municipal Airport'),
('KINK', 'US/Central', 'Winkler County Airport'),
('KMDD', 'US/Central', 'Midland Airpark'),
('KAZE', 'US/Eastern', 'Hazlehurst Airport'),
('KAFP', 'US/Eastern', 'Anson County Airport - Jeff Cloud Field'),
('KBPG', 'US/Central', 'Big Spring Mc Mahon-Wrinkle Airport'),
('KBAC', 'US/Central', 'Barnes County Municipal Airport'),
('KGGW', 'US/Mountain', 'Glasgow Valley County Airport Wokal Field'),
('KE11', 'US/Central', 'Andrews County Airport'),
('KALS', 'US/Mountain', 'San Luis Valley Regional Airport/Bergman Field'),
('KAYS', 'US/Eastern', 'Waycross Ware County Airport');
